### ISSUE TITLE
hardcoded changes in head.S

### ISSUE THREAD

**Issue by amery** [linux-sunxi/linux-sunxi#1]
in `arch/arm/kernel/head.S` we are hardcoding (9aae53f907709010497ac6db7338786cb0c1fbe6) two chunks of ASM, the first sets the machine id (which is in fact job of the bootloader) and about the second Tom said today on IRC.

```
09:59:15 < hipboi> ok, i checked with my workmate
09:59:42 < hipboi> it's maps the memory of the sys_config
10:00:37 < hipboi> at the 48MiB offset of 0x40000000
```

but we can't just cut it out and my knowledge about ARM's linux booting process is still too limited to know. hints?

**Comment by hno** [comment]
The early mapping of script.bin/sys_config seems to be only for being able to read gps and g2d memory size configurations. These could just as well be passed as command line arguments.

**Comment by amery** [comment]
I'm not sure it's wise to change the scope of script.bin and increase the dependency on the bootloader while on one side you have tons of people with A10-based devices that will expect to run our kernel without touching their factory-provided bootloader chain, and on another there is people expecting to be able to boot linux without uboot (kexecboot for example)

**Comment by hno** [comment]
mån 2012-04-09 klockan 02:19 -0700 skrev Alejandro Mery:

> I'm not sure it's wise to change the scope of script.bin and increase
> the dependency on the bootloader while on one side you have tons of
> people with A10-based devices that will expect to run our kernel
> without touching their factory-provided bootloader chain, and on
> another there is people expecting to be able to boot linux without
> uboot (kexecboot for example)

I very narrow focuses

a) Getting the A10 support in good shape so it can be digested.

b) The same but in shape for submitting to mainline

c) A kernel that I am happy with for our project

And I see it likely that details on script.bin loading / addressing may
need to change to reach those goals.

I do not want to include the requirement of easy transition from legacy
A10 setup to a more saner at this stage. It can easily be solved with a
compatibility thing later on which is likely either a small second-stage
bootloader prepended to the kernel or a small embedded initrd.

Regards
Henrik

**Comment by amery** [comment]
fair enough ;-)
