### ISSUE TITLE
support for Elan eKTF Touchscreen

### ISSUE THREAD

**Issue by psachin** [linux-sunxi/linux-sunxi#100]
Is there any support available for **elants** ? I found a patch
[here](https://patchwork.kernel.org/patch/1661891/). Is it going to be implemented for _linux-sunxi_?

**Comment by rzk** [comment]
You are welcome to integrate it to one of our stable trees (sunxi-3.0/3.4) and send patch to http://linux-sunxi.org/Mailing_list if you have the appropriate hardware to test it.

If you have a chance, you can also test these two: https://github.com/linux-sunxi/linux-sunxi/commit/82bcb1aaff994645ee4f1cf1d7bf67da84640eed https://github.com/linux-sunxi/linux-sunxi/commit/6467561ea0cd5acd2fa7bd564d5490085e788d1f
They come from newest sourcedrop.

**Comment by psachin** [comment]
I mailed the developer, this patch only works for kernel version 3.7 and above
