### ISSUE TITLE
android 4.2 jellybean support?

### ISSUE THREAD

**Issue by niftylettuce** [linux-sunxi/linux-sunxi#101]
can anyone link me to the development of android for allwinner a13?

**Comment by rzk** [comment]
Please use http://linux-sunxi.org/Mailing_list

'Official' Allwinner sources are available at https://github.com/allwinnerwk
Unofficial port is at https://github.com/allwinner-dev-team

**Comment by niftylettuce** [comment]
@rzk thank you, can you please provide me a link to the particular branch/repo for 4.2+ jellybean on A13 boards?

**Comment by rzk** [comment]
I believe only 4.1.x is supported officially by allwinner, wait till they push their newest stuff to @allwinnerwk or port it yourself using 4.1.x sources as a base. As far as I know they are now busy with sun6i and 4.2 will be available with it release, hopefully, with updates for sun[4/5]i.

**Comment by niftylettuce** [comment]
@rzk thank you for all of the info!  much appreciated.  last question if you don't mind, which particular repo should I be looking into?  might save me some time if you know it off hand.  cheers.

**Comment by niftylettuce** [comment]
i think this is it, https://github.com/allwinner-dev-team/android_frameworks_base -- can you confirm?

**Comment by rzk** [comment]
Look for info about android build system and how to use repo tool. If you have questions about @allwinner-dev-team, find Turl at #arm-netbook@freenode, he hosts that.
