### ISSUE TITLE
This broke usb-audio 

### ISSUE THREAD

**Issue by ntm12** [linux-sunxi/linux-sunxi#106]
This commit :
https://github.com/linux-sunxi/linux-sunxi/commit/85b6519481962e56e69c7a31ae67293352fee2d3
totally broke usb-audio ,
tested with PCM2704 USB DAC
If i'm revert this small changes ,than  all goes fine - usb audio works

**Comment by amery** [comment]
Hi, can you try stage/sunxi-3.0 or stage/sunxi-3.4 branches?

**Comment by ntm12** [comment]
this commit from "stage/sunxi-3.0" fixes the problem :
https://github.com/linux-sunxi/linux-sunxi/commit/03d7dfff74f3e78e61ff4127793b917d9ce4c63b .
usb-audio in sunxi-3.0 now works again ,thank you .

**Comment by amery** [comment]
this has been merged to sunxi-3.0 and sunxi-3.4 already.
