### ISSUE TITLE
appeared red frame (in all A13 ROM, even JB)

### ISSUE THREAD

**Issue by monteship** [linux-sunxi/linux-sunxi#114]
appears only when some action!
and hide! 
there i edit my screenshot to show that issue!
https://docs.google.com/file/d/0B_ziT-oEcygsbFRYUkxVY3JfZkE/edit

**Comment by steev** [comment]
This occurs because it takes a while to render. There isn't a whole lot
that can be done, as a few different things cause it.

**Comment by techn** [comment]
So, this problem is seen with stock image?

**Comment by steev** [comment]
I am pretty sure it's part of the developer options to show GPU overdraw.
Something may have it enabled even if the developer option is off. It has
been a while since I've touched android but I thought there was a second
option to draw it when things were running a bit slow.

**Comment by monteship** [comment]
It is present only in setings! there is no way to off this?

**Comment by amery** [comment]
if it's an alert of bad perfomance you don't really want to disable it. but to find the cause of the performance issue.

**Comment by monteship** [comment]
ok! did you help me?

**Comment by turl** [comment]
This is not a bug; it's an Android feature. Don't run engineering/debug builds and/or disable it on the developer settings ("Strict mode") if you don't like it.
