### ISSUE TITLE
Incompatibility between enc28j60.c and sunxi_spi.c

### ISSUE THREAD

**Issue by vinifr** [linux-sunxi/linux-sunxi#116]
There is a test that precludes the use enc28j60.c in its original form:

sunxi_spi.c: LINE 812:
 /\* check in the __spi_async if use half duplex */
    if(t->tx_buf && t->rx_buf)
        return -EINVAL;

This does not allow spi_read_buf() to accomplish its task:

enc28j60.c: LINE 92
struct spi_transfer t = {
        .tx_buf = tx_buf,
        .rx_buf = rx_buf,
        .len = SPI_OPLEN + len,
    };

Lorenzo proposed to change enc28j60.c this way: http://pastebin.com/ZxYkuebs

What would be the best solution?

**Comment by amery** [comment]
please submit to the linux-sunxi mailinglist.

**Comment by vinifr** [comment]
Hi amery,

Lorenzo already posted on the mailing list: https://groups.google.com/forum/?fromgroups=#!topic/linux-sunxi/unWV4VIZXoY

We can also change spi_sunxi.c.

What do you think?

**Comment by amery** [comment]
sounds fair, but please tell so on the ML and submit the git formatted commit including a description of the problem and the explaination of the fix. there are several devs which aren't subscribed to this issue tracker.

**Comment by vinifr** [comment]
Sorry for reopen.

 I have a doubt... in the case of mismatch between chip driver and platform driver, which must be changed?  taking into account that enc28j60.c is in the mainline.

I ask because with atmel_spi.c(for example), enc28j60.c accomplish its task normally, not required any changes.

**Comment by amery** [comment]
the sunxi driver should be fixed to coexist with mainlined code, not the other way around.
