### ISSUE TITLE
Kernel 3.4 not booting on Cubieboard

### ISSUE THREAD

**Issue by RipZ** [linux-sunxi/linux-sunxi#126]
Using sun4i-crane-defconfig. 
Logs:

Starting kernel ...

<6>Booting Linux on physical CPU 0
<5>Linux version 3.4.29+ (root@i7-buildhost) (gcc version 4.5.1 (Sourcery G++ Lite 2010.09-50) ) #6 PREEMPT Sun Apr 7 00:09:54 MSK 2013
CPU: ARMv7 Processor [413fc082] revision 2 (ARMv7), cr=10c53c7d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
Machine: sun4i
<3>INITRD: 0x41000000+0x000ee096 is not a memory region - disabling initrd
<6>Memory Reserved:
<6>     SYS  : 0x43000000 - 0x4300ffff  (  64 kB)
<4>Not enough memory to reserve memory for VE
<4>Not enough memory to reserve memory for G2D
<4>Not enough memory to reserve memory for LCD
Memory policy: ECC disabled, Data cache writeback
<0>Kernel panic - not syncing: ERROR: Failed to allocate 0x1000 bytes below 0x0.

[<c0014038>](unwind_backtrace+0x0/0x11c) from [<c0521c24>](panic+0x74/0x1b4)
[<c0521c24>](panic+0x74/0x1b4) from [<c07a246c>](memblock_alloc_base+0x2c/0x34)
[<c07a246c>](memblock_alloc_base+0x2c/0x34) from [<c079c4b4>](early_alloc_aligned+0xc/0x2c)
[<c079c4b4>](early_alloc_aligned+0xc/0x2c) from [<c079cf80>](paging_init+0x4b0/0x73c)
[<c079cf80>](paging_init+0x4b0/0x73c) from [<c079aa64>](setup_arch+0x4f4/0x7a4)
[<c079aa64>](setup_arch+0x4f4/0x7a4) from [<c0797504>](start_kernel+0x78/0x2cc)
[<c0797504>](start_kernel+0x78/0x2cc) from [<40008040>](0x40008040)
<0>Rebooting in 2 seconds..Reboot failed -- System halted

**Comment by rzk** [comment]
If you want to run android (otherwise, why you decided to use crane config?), you should consider finding official sources and guide. iirc, there were ones from @matson-hall

3.4 is somewhat 'beta' kernel and most of the users run 3.0 stable branch with native linux userspace using sun4i_defconfig.

If you want detailed discussion of your problem, hop over to our mailing list: https://groups.google.com/forum/#!forum/linux-sunxi

**Comment by amery** [comment]
@RipZ: the problem is that the u-boot preinstalled on the NAND doesn't properly pass ATAG info. in order to use any newer kernel from nand (or 3.0 with allwinner boothacks disabled) you need to replace nanda's linux/u-boot.bin with one build from the lichee-dev branch of u-boot-sunxi.

**Comment by RipZ** [comment]
Thanks, @amery. I'll try later to replace u-boot.bin.
