### ISSUE TITLE
DDC TTY cannot be compiled (kernel: 3.4)

### ISSUE THREAD

**Issue by nvdl** [linux-sunxi/linux-sunxi#127]
Compiling as a module:

CC [M]  drivers/char/dcc_tty.o
drivers/char/dcc_tty.c:29:36: error: 'SPIN_LOCK_UNLOCKED' undeclared here (not in a function)
make[2]: **\* [drivers/char/dcc_tty.o] Error 1
make[1]: **\* [drivers/char] Error 2
make: **\* [drivers] Error 2
cp: cannot stat `/mnt/nas/kernel/linux-sunxi-3.4/modules.builtin': No such file or directory
make: **\* [_modinst_] Error 1

**Comment by wingrime** [comment]
patch sended

**Comment by amery** [comment]
thank you.
