### ISSUE TITLE
drivers/media/video/sun4i_csi/csi0/sun4i_drv_csi.c inlining problem

### ISSUE THREAD

**Issue by bnolsen** [linux-sunxi/linux-sunxi#13]
With gcc-4.7 (from arch linux) there is a problem with compiling drivers/media/video/sun4i_csi/csi0/sun4i_drv_csi.c

Error is that functions are declared inline yet no function bodies are found.

The calls: bsp_csi_set_buffer_address and bsp_csi_int_clear_status are the culprits.

drivers/media/video/sun4i_csi/include/sun4i_csi_core.h  contains the inline function prototypes.

drivers/media/video/sun4i_csi/csi1/sun4i_drv_csi.c seems to have the inline function bodies.

**Comment by amery** [comment]
fixed with 3414932bd756d410e934d220743c593d11270994
