### ISSUE TITLE
allwinner-v3.0-android-v2 compile error

### ISSUE THREAD

**Issue by tsynik** [linux-sunxi/linux-sunxi#14]
Hi, I have trouble compile allwinner-v3.0-android-v2 branch for sun4i_crane platform.

Default config used.

Android USB gadget driver give me that error under Mac OS X:

  CC      drivers/usb/gadget/android.o
drivers/usb/gadget/android.c: In function 'android_disable':
drivers/usb/gadget/android.c:221:1: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
drivers/usb/gadget/android.c:226:12: error: invalid storage class for function 'adb_function_init'
drivers/usb/gadget/android.c:235:13: error: invalid storage class for function 'adb_function_cleanup'
drivers/usb/gadget/android.c:241:12: error: invalid storage class for function 'adb_function_bind_config'
drivers/usb/gadget/android.c:246:13: error: invalid storage class for function 'adb_android_function_enable'
drivers/usb/gadget/android.c:258:13: error: invalid storage class for function 'adb_android_function_disable'
...
etc

The same errors under linux build environment.

Also, found revert for Android USB gadget and info about new AOSP code give errors in CM9:

https://github.com/faux123/msm8660-htc-ics/pull/3/files

**Comment by amery** [comment]
`drivers/usb/gadget/android.c` should compile fine now, please test.
