### ISSUE TITLE
cannot get iw tool to work - no such device -19

### ISSUE THREAD

**Issue by radagasp** [linux-sunxi/linux-sunxi#146]
I compiled the kernel successfully and set up a rootfs and deployed to my cubie, which works well. iwconfig tool can pick up the realtek wireless usb dongle I am using, but when I try to use the iw tool it says no such device with error code -19

does anyone know why this might be happening?

**Comment by rbedemann** [comment]
how did you solve the problem?

**Comment by jpolly168** [comment]
Start a new thread. That one was closed 9 months ago and it may have been
unanswered from what I see

Justin
