### ISSUE TITLE
ppp_generic not loading

### ISSUE THREAD

**Issue by radagasp** [linux-sunxi/linux-sunxi#147]
I tried to load the ppp_generic module after configuring its support in menuconfig, and building the kernel.  It gives me an error along the lines of:

ppp_generic: disagrees about version of symbol xxx
ppp_generic: unknown symbol xxx (err -22)

It actually gives me a couple of these errors, and then, 

ERROR: could not insert `ppp_generic`: Invalid Argument

 has anyone had any experience with this? The interwebz are pretty empty on this issue.

**Comment by romanrm** [comment]
Stop creating pointless issues, go ask at the mailing list about this, it is not a bug in linux-sunxi if you don't know how to do something.

**Comment by radagasp** [comment]
oh relax
