### ISSUE TITLE
undefined reference to `__tracepoint_mmc_blk_rw_end'

### ISSUE THREAD

**Issue by djahma** [linux-sunxi/linux-sunxi#150]
Hi there,

I get this error at the end of compilation:
 LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  LD      .tmp_vmlinux1
drivers/built-in.o: In function `rcu_read_unlock_sched_notrace':
/home/djahma/Documents/arm/linux-sunxi/linux-sunxi-sunxi-3.4/include/linux/rcupdate.h:843: undefined reference to`__tracepoint_mmc_blk_rw_end'
/home/djahma/Documents/arm/linux-sunxi/linux-sunxi-sunxi-3.4/include/linux/rcupdate.h:843: undefined reference to `__tracepoint_mmc_blk_erase_start'
/home/djahma/Documents/arm/linux-sunxi/linux-sunxi-sunxi-3.4/include/linux/rcupdate.h:843: undefined reference to`__tracepoint_mmc_blk_erase_end'
/home/djahma/Documents/arm/linux-sunxi/linux-sunxi-sunxi-3.4/include/linux/rcupdate.h:843: undefined reference to `__tracepoint_mmc_blk_rw_start'
make[1]: **\* [.tmp_vmlinux1] Error 1
make: **\* [sub-make] Error 2

In "make gconfig" I chose AllWinner A10 system type. That's the only thing I changed from default config. Along compilation I got a few driver errors, so I returned in gconfig to unselect the culprits, and resumed compilation with the following parameters:
djahma@StudioXPS:~/Documents/arm/linux-sunxi/linux-sunxi-sunxi-3.4$ sudo make ARCH=arm O=/home/djahma/Documents/arm/buildsunxi CROSS_COMPILE=arm-linux-gnueabihf- uImage

On a side question, I'd be interested in knowing where is a good place to discuss installing linux on a basic chinese A10 tablet because I'm tearing my hair off at the moment. 

Thanks

**Comment by djahma** [comment]
I tried compiling with arm-linux-gnueabi tool-chain instead of arm-linux-gnueabihf but the same error occurred again.
Both tool-chains are from ubuntu 12.04 repos.

**Comment by arokux** [comment]
Hi,

I'm not sure you are building the kernel correctly. Specifically your
configuration steps is wrong (at least what you show). Please follow the
instructions here [1] and report your success/failure.

Thanks,
Arokux

[1] http://linux-sunxi.org/FirstSteps#Building_the_kernel

**Comment by djahma** [comment]
following the FirstSteps guide helped indeed. thanks.
Now new issues are arising to get the tablet features working, but at least, this first error is solved
