### ISSUE TITLE
G2D support on A20

### ISSUE THREAD

**Issue by kklem0** [linux-sunxi/linux-sunxi#151]
https://github.com/cubieplayer/Cubian/issues/94#issuecomment-24062966
According to @ssvb it should be quite easy to enable, but I don't have much time to dig into this, so it would be cool if someone can make a patch.

**Comment by rzk** [comment]
Please, use our mailing list, dont open github issues.

We already have a bunch of guys working on g2d for sun7i, progress can be found here: https://groups.google.com/forum/#!topic/linux-sunxi/sVAjv-h2uCw

If you can - please help testing by applying the patches to your local tree and reporting the results.
