### ISSUE TITLE
Error using web-camera(ep packet is too big)

### ISSUE THREAD

**Issue by Devider** [linux-sunxi/linux-sunxi#159]
I have a problem using a web camera (defender c-110) on mk802ii
$ avconv -f video4linux2 -r 5 -s 640x480 -i /dev/video0 out.avi
     avconv version 0.8.6-6:0.8.6-1, Copyright (c) 2000-2013 the Libav developers
     built on Mar 24 2013 22:04:47 with gcc 4.6.3
     [video4linux2 @ 0x168bc40] The driver changed the time per frame from 1/5 to 1/30
     [video4linux2 @ 0x168bc40] ioctl(VIDIOC_STREAMON): Message too long
     /dev/video0: Message too long
Here is dmesg out:
[ 54.444469] usb 1-1: new high-speed USB device number 2 using sw_hcd_host0
[ 54.616376] uvcvideo: Found UVC 1.00 device USB2.0 Camera (1871:0101)
[ 54.647092] input: USB2.0 Camera as /devices/platform/sw_hcd_host0/usb1/1-1/1-1:1.0/input/input2
[ 54.676522] WRN:L3147(drivers/usb/sunxi_usb/hcd/core/sw_hcd_host.c):ERR: not support type(3)
[ 245.798930] WRN:L2841(drivers/usb/sunxi_usb/hcd/core/sw_hcd_host.c):ERR: sw_hcd_urb_enqueue, ep packet is too big, maxpacket = 5116
[ 245.821388] uvcvideo: Failed to submit URB 0 (-90).
[ 245.858203] WRN:L3147(drivers/usb/sunxi_usb/hcd/core/sw_hcd_host.c):ERR: not support type(3)

**Comment by romanrm** [comment]
Which USB port do you use, not the OTG port via an adapter by any chance?

**Comment by Devider** [comment]
Yes, I used OTG port, it works fine using "normal" USB port. Thanks a lot!

**Comment by hunterhu** [comment]
Hi Devider, I came across the same issue, I had to use an OTG cable to connect to my tablet; and got the packet is too big error.

What do you mean by normal USB port? the UVC usb webcam won't connect unless with a OTG adaptor cable.

thanks.

**Comment by brNX** [comment]
Hi all , 

does a workaround exist for this problem (without using a normal port) or is it a hardware limitation ? 

Kind regards

**Comment by kk90** [comment]
Hello same problem here, is there a workaround to use webcam with OTG port?

I get

[video4linux2 @ 0xf98bc0] ioctl(VIDIOC_STREAMON): Message too long
/dev/video0: Mess[sw_hcd]: sw_hcd_urb_dequeue, sw_hcd(cf8dd8f0, 0x0, 0x3f),urb(cfa72600, 16, 0), dev = 2, ep = 3, dir = in
WRN:L3147(drivers/usb/sunxi_usb/hcd/core/sw_hcd_host.c):ERR: not support type(3)
