### ISSUE TITLE
dcc_tty.c in 3.0 v2

### ISSUE THREAD

**Issue by kenchy** [linux-sunxi/linux-sunxi#16]
Needed to change line in drivers/char/dcc_tty.c to match v1.

Offending line is

static spinlock_t g_dcc_tty_lock = SPIN_LOCK_UNLOCKED;  in v2

static DEFINE_SPINLOCK(g_dcc_tty_lock);  in v1

 (will try to track down root cause),

**Comment by amery** [comment]
thanks for reporting this. i didn't realize sun4i_deconfig was that different in both tree. fixed now.
