### ISSUE TITLE
Error during compilation - mach/clock.h

### ISSUE THREAD

**Issue by devandcom** [linux-sunxi/linux-sunxi#163]
When I compile 3.4 kernel I receive this error...

drivers/gpu/mali/mali/platform/mali400-pmu/mali_platform.o
drivers/gpu/mali/mali/platform/mali400-pmu/mali_platform.c:22:24: fatal error: mach/clock.h: No such file or directory
compilation terminated.
make[4]: **\* [drivers/gpu/mali/mali/platform/mali400-pmu/mali_platform.o] Errore 1
make[3]: **\* [drivers/gpu/mali/mali] Errore 2
make[2]: **\* [drivers/gpu/mali] Errore 2
make[1]: **\* [drivers/gpu] Errore 2
make: **\* [drivers] Errore 2

Can you help me ?
Thank you

**Comment by jpolly168** [comment]
You're missing a file or compiling wrong.

**Comment by amery** [comment]
did you download a .zip from github? those don't include symlinks, please do a proper git clone.

**Comment by devandcom** [comment]
I make :
 git clone https://github.com/linux-sunxi/linux-sunxi
cd linux-sunxi/
git checkout wip/linux-sunxi-3.4/cubieboard

apparently without error

I do something wrong?

**Comment by amery** [comment]
never use wip/ branches. unless you know what you are doing stick with the default (sunxi-3.4) or at most stage (stage/sunxi-3.4) branch.

**Comment by devandcom** [comment]
I tried the default branch
I tried 3 different toolchain
I'm compiling from ubuntu 12.04, I tried also debian wheezy
I receive the same error :(
Could it be that I miss some development library ?

**Comment by amery** [comment]
please try a fresh checkout. something is very weird there. the nightlies are done on ubuntu 12.04 using linaro's toolchain.

**Comment by devandcom** [comment]
I rewrite .config with the default : 
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- sun7i_defconfig
the error has disappeared
:)
