### ISSUE TITLE
make deb-pkg target fails (because make headers_check fails)

### ISSUE THREAD

**Issue by kenchy** [linux-sunxi/linux-sunxi#17]
I am assuming this is because the androidisation of the kernel messes up the header file structure, but make deb-pkg fails, because behind the scenes make headers_check fails, on allwinner-v3.0-android, and allwinner-v3.0-android-v2. This is more for information than anything, as the same did not apply to the 3.3 tree.

If you disable the "make headers_check" in scripts/package/builddeb, then it succeeds in building the packages, though how useful the headers package is unknown. Although there are problems with arm headers packages anyway as I believe the "mach-xxx" headers are not included (certainly true when buidling kirkwood targets).

**Comment by amery** [comment]
I have no idea how that `headers_check` works, but switching to `upstream-android-3.0` (android kernel base) gives the very same errors.

```
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- headers_check
  CHK     include/linux/version.h
  CHECK   include/linux (364 files)
$PWD/usr/include/linux/if_pppox.h:24: included file 'linux/if_pppolac.h' is not exported
$PWD/usr/include/linux/if_pppox.h:25: included file 'linux/if_pppopns.h' is not exported
$PWD/usr/include/linux/kernel.h:65: userspace cannot reference function or variable defined in the kernel
$PWD/usr/include/linux/kernel.h:97: userspace cannot reference function or variable defined in the kernel
$PWD/usr/include/linux/quota.h:175: userspace cannot reference function or variable defined in the kernel
$PWD/usr/include/linux/soundcard.h:1054: userspace cannot reference function or variable defined in the kernel
make[2]: *** [$PWD/usr/include/linux/.check] Error 123
```

so this will probably have to wait until there is a non-androidized tree.

**Comment by steev** [comment]
Honestly, i've never ever ever gotten a make deb-pkg to work, even on my debian systems.  I'd not worry too much about it.

**Comment by amery** [comment]
is there something we have to do in the tree to make easier the generation of .deb files out of the box?

**Comment by steev** [comment]
I'm not sure.  I don't tend to build debs, as I'm more of a Gentoo guy and we can easily handle just copying a uImage into /boot after doing a make modules_install ;)  That said, when I DO have to build debs, I normally use the debian 'make-kpkg' command (from kernel-package) to build them.  Something akin to make-kpkg --revision year.month --uc --us --cross-compile arm-none-linux-gnueabi- --jobs=9 --rootcmd=fakeroot --arch armel $target (binary (builds all), kernel_image (builds just the kernel package, kernel_header(s?) builds just the headers package) and so forth)

**Comment by amery** [comment]
ah, great... I thought we needed to mess with `debian/` stuff

**Comment by amery** [comment]
`make headers_check` works fine in the androidless 3.3 branch

**Comment by kenchy** [comment]
I have fixed this(with help from internet). In include/linux/Kbuild add

header-y += if_pppolac.h
header-y += if_pppopns.h

under 

header-y += if_pppox.h

simples!
