### ISSUE TITLE
USB HDD docking does not work with Cubieboard2

### ISSUE THREAD

**Issue by hgonzale** [linux-sunxi/linux-sunxi#170]
I have a Rosewill RX-DU300 HDD docking with a 1TB seagate hard drive. When plugged in I get the following error in dmesg:
[  110.546104] usb 1-1: New USB device found, idVendor=174c, idProduct=5106
[  110.546136] usb 1-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  110.546165] usb 1-1: Product: AS2105
[  110.546187] usb 1-1: Manufacturer: ASMedia
[  110.546954] usb 1-1: usb_probe_device
[  110.546992] usb 1-1: configuration #1 chosen from 1 choice
[  115.546016] usb 1-1: khubd timed out on ep0out len=0/0
[  115.546077] usb 1-1: can't set config #1, error -110

The docking works fine with other linux machines, and the Cubieboard2 also works fine with other external drives.

Here is the output of .config, dmesg, /proc/ccmu, and the various memory locations of interest:
http://sprunge.us/hghc

**Comment by jpolly168** [comment]
Does it read without the dock? it Maybe a time error.

**Comment by hgonzale** [comment]
The hard drive works fine (both with or without the dock) on every other machine I've tried it on. I'm not sure how to check if it is a time error though.

**Comment by jpolly168** [comment]
I am not the most tech capable of people on here, but I would suggest doing
some research on this "usb 1-1: can't set config
#1https://github.com/linux-sunxi/linux-sunxi/issues/1,
error -110" in Google. Most likely that device is just not going to work
without a patch. If i had more time to look at it I might be able to help;
and I will try. I would guess this is a bus time error. This happens in
Linux sometimes if the config is missing or wrong.

On Thu, Jan 30, 2014 at 8:26 PM, Humberto Gonzalez <notifications@github.com
