### ISSUE TITLE
suggestion: versioning

### ISSUE THREAD

**Issue by DaLiV** [linux-sunxi/linux-sunxi#194]
as we can refer to https://www.kernel.org/
3.14.7 - is stable branch  and 3.15 - is a mainline.
so why not use that information as reference point for main development line instead of 3.4 ?
as also reffered to the http://linux-sunxi.org/Linux_mainlining_effort#Merged_into_3.15
= we can see the mainline kernel already have many things integrated but in 3.4 that is even not quite exactly declared as supported ...

suggestion: make smaller amount of branches - but which will live instead of dead bulk ...
as example leave as obsoleting : sunxi-(2.6, 3.0, 3.4)
and move to the main stable version equal with kernel.org stable

**Comment by amery** [comment]
we can't deprecate 3.4 until user-critical features like... display are available on mainline. there is an experimental new stable branch sunxi-3.14 (with 3.15 stuff backported) which will get the missing bits forward-ported eventually...
