### ISSUE TITLE
linux-sunxi for kernel 3.15?

### ISSUE THREAD

**Issue by jiapei100** [linux-sunxi/linux-sunxi#195]
Just wondering if there is any progress on kernel 3.15 for linux-sunxi?

cheers

**Comment by arokux** [comment]
On Thu, Jun 26, 2014 at 5:12 PM, JIA Pei notifications@github.com wrote:

> Just wondering if there is any progress on kernel 3.15 for linux-sunxi?

http://linux-sunxi.org/Linux_mainlining_effort

**Comment by jiapei100** [comment]
It's weird that you are interested in allwinner products, and build up the wiki pages for them. Are you working for this company?

Cheers
Pei

**Comment by amery** [comment]
this is purely voluntary work for improving the open source support of a platform we like. no one on this community works for allwinner or is paid to contribute.

**Comment by arokux** [comment]
On Mon, Jun 30, 2014 at 6:48 PM, JIA Pei notifications@github.com wrote:

> It's weird that you are interested in allwinner products, and build up the
> wiki pages for them. Are you working for this company?

why are you asking if there is progress on mainline if you find it weird
people works on it? the allwinner will never ever mainline, in case you
didn't know.
