### ISSUE TITLE
cp: cannot stat `drivers/net/wireless/bcm4330/firmware/mw269v3_fw.bin': No such file or directory

### ISSUE THREAD

**Issue by huaixiaoz** [linux-sunxi/linux-sunxi#20]
Maybe  you have forget put these into  the fold ...
cp: cannot stat `drivers/net/wireless/bcm4330/firmware/mw269v3_fw.bin': No such file or directory

And This  is  the  output error :

Image Name:   Linux-3.0.31+
Created:      Sat May 19 20:57:10 2012
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    4042472 Bytes = 3947.73 kB = 3.86 MB
Load Address: 40008000
Entry Point:  40008000
  Image arch/arm/boot/uImage is ready
`arch/arm/boot/uImage' ->`output/uImage'
`arch/arm/boot/zImage' ->`output/zImage'
cp: cannot stat `drivers/net/wireless/bcm4330/firmware/mw269v3_fw.bin': No such file or directory

i  used  the old(3.08+ /based my table  ) instead of it

**Comment by amery** [comment]
file added in 9f2c962 please confirm it solves the issue
