### ISSUE TITLE
 [experimental/sunxi-3.10] Compilation error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’

### ISSUE THREAD

**Issue by lauhub** [linux-sunxi/linux-sunxi#208]
I try to compile the experimental/sunxi-3.10 branch and I get the following error:

```
  ...
  CC      fs/proc/base.o
fs/proc/base.c: In function ‘oom_adjust_permission’:
fs/proc/base.c:1016:7: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
fs/proc/base.c:1024:28: error: invalid operands to binary == (have ‘kuid_t’ and ‘int’)
  ...
```

I compile (without cross compiling) on an A20-OlinuXino-MICRO with Debian Wheezy (Linux 3.4.67+ #6 SMP PREEMPT Fri Nov 1 17:32:40 EET 2013 armv7l GNU/Linux)

My configuration file : [a10lime_defconfig](https://gist.github.com/lauhub/53f59657460be69a0ac6#file-a10lime-defconfig)

The command line I used: 

```
$ make a10lime_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#

$ make -j4 uImage
```

It seems the error comes from the sources (same error with command line `make ARCH=arm  -j4 uImage`)
I retrieved these sources using the following command:

``` bash
git clone -b experimental/sunxi-3.10 --single-branch https://github.com/linux-sunxi/linux-sunxi linux-sunxi-3.10
```

**Comment by leon-anavi** [comment]
I experienced similar issues with the experimental branch for 3.10. My research showed that it is caused by the introduction of a structure kuid_t. I submitted a patch with fixed almost a month ago but it is still not merged: https://github.com/linux-sunxi/linux-sunxi/pull/204

**Comment by lauhub** [comment]
OK, thanks, I'll give it a try

**Comment by oliv3r** [comment]
3.10 is highly experimental and even marked for removal.

Do not use or mess with 3.10. It basically is, in its current form, 
nothing more then 3.10 with later patches backported. So using 3.17 you 
get more new stuff.

Do Not Use.

Olliver
On 05-09-14 00:58, lauhub wrote:

> OK, thanks, I'll give it a try
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/linux-sunxi/linux-sunxi/issues/208#issuecomment-54557443.

## 

Met vriendelijke groeten, Kind regards, 与亲切的问候

Olliver Schinagl
Research & Development
Ultimaker B.V.
http://www.ultimaker.com

**Comment by lauhub** [comment]
OK, thank you for this information. I suggest to update this page : [http://linux-sunxi.org/Linux_Kernel]

It indicates that the 3.10 version is experimental although other are highly experimental. I chose 3.10 because of this.
