### ISSUE TITLE
ft5x_ts doesnt work on A20 Olinuxino

### ISSUE THREAD

**Issue by mushketer888** [linux-sunxi/linux-sunxi#212]
I am using latest kernel 3.4.103 but ft5x doesnt work.
i have pins configured properly in .fex

also to notice: it gave me errors and was unable to share irq, so i changed:
err = request_irq(SW_INT_IRQNO_PIO, ft5x_ts_interrupt, IRQF_TRIGGER_FALLING | IRQF_SHARED, "ft5x_ts", ft5x_ts);
to
err = request_irq(SW_INT_IRQNO_PIO, ft5x_ts_interrupt,IRQF_SHARED, "ft5x_ts", ft5x_ts);

and it started to load at least
but as it seems interrupt doesnt work at all (chip is working , tested with i2ctools)
there is something about "trigger falling" interrupt

more info can be seen in: https://www.olimex.com/forum/index.php?topic=3734.0

**Comment by wingrime** [comment]
Please consider that not all pins have IRQ ability

**Comment by mushketer888** [comment]
Thanks
I also thought about it
Will try

**Comment by mushketer888** [comment]
Thanks! It works
Yeap..not all pins can be used for interrupts

**Comment by vinifr** [comment]
I do not understand this code. So that it request a pin and do not use it? 
...
gpio_int_hdle = gpio_request_ex("ctp_para", "ctp_int_port");
...
request_irq(SW_INT_IRQNO_PIO,xxx);

Should not be?
int irq = gpio_to_irq(gpio_int_hdle);
request_irq(irq,xxx);
