### ISSUE TITLE
Every VLAN frame is logged at the "INFO" level

### ISSUE THREAD

**Issue by romanrm** [linux-sunxi/linux-sunxi#213]
@mnemoc I assume you missed this, otherwise a no-brainer patch which fixes the shockingly-broken current behavior:
http://permalink.gmane.org/gmane.comp.hardware.netbook.arm.sunxi/10568
can we please have this applied?
Thanks

**Comment by amery** [comment]
thanks, applied on the stage branch. if there are other outstanding patches for 3.4 please poke me.
