### ISSUE TITLE
error Your compiler is too buggy(linaro 4.8.2 Lubuntu : sunxi-next 3.18.0-rc3)

### ISSUE THREAD

**Issue by gooseberrypi** [linux-sunxi/linux-sunxi#217]
CC      arch/arm/kernel/asm-offsets.s
arch/arm/kernel/asm-offsets.c:53:2: error: #error Your compiler is too buggy; it is known to miscompile kernels
 #error Your compiler is too buggy; it is known to miscompile kernels
  ^
arch/arm/kernel/asm-offsets.c:54:2: error: #error and result in filesystem corruption and oopses.
 #error and result in filesystem corruption and oopses.
  ^
make[1]: **\* [arch/arm/kernel/asm-offsets.s] Error 1
make: **\* [prepare0] Error 2

**Comment by oliv3r** [comment]
Well the code complains about your compiler being too buggy. Maybe open a issue up with your compiler supplier.
Even worse, you complain about the 3.18.0-rc3 kernel (vanilla mainline kernel) on the linux-sunxi github (where you really should only complain about sunxi driver patches or 3.4 kernels). So the wrong place really.
I'm using arm-linux-gnueabihf-gcc (Ubuntu/Linaro 4.9.1-16ubuntu6) 4.9.1
on one machine and it compiles beautifully.

**Comment by gooseberrypi** [comment]
Sorry sir , and Thanks.
