### ISSUE TITLE
Can't compile sunxi-3.4.104 branch. Stops on sndi2s.c error.

### ISSUE THREAD

**Issue by ryba84** [linux-sunxi/linux-sunxi#221]
Tested with gcc-4.7 (Linaro cross toolchain) and gcc-4.9 (Debian testing cross toolchain). Compiler output:
  LD      sound/soc/sh/built-in.o
  LD      sound/soc/sunxi/built-in.o
  CC [M]  sound/soc/sunxi/sunxi-codec.o
  LD      sound/soc/sunxi/hdmiaudio/built-in.o
  CC [M]  sound/soc/sunxi/hdmiaudio/sunxi-hdmiaudio.o
  CC [M]  sound/soc/sunxi/hdmiaudio/sunxi-hdmipcm.o
  CC [M]  sound/soc/sunxi/hdmiaudio/sndhdmi.o
  CC [M]  sound/soc/sunxi/hdmiaudio/sunxi-sndhdmi.o
  LD      sound/soc/sunxi/i2s/built-in.o
  CC [M]  sound/soc/sunxi/i2s/sunxi-i2s.o
  CC [M]  sound/soc/sunxi/i2s/sunxi-i2sdma.o
  CC [M]  sound/soc/sunxi/i2s/sndi2s.o
sound/soc/sunxi/i2s/sndi2s.c:49:51: error: ‘SNDRV_PCM_FMTBIT_S20_LE’ undeclared here (not in a function)
                        SNDRV_PCM_FMTBIT_S18_3LE | SNDRV_PCM_FMTBIT_S20_LE)
                                                   ^
sound/soc/sunxi/i2s/sndi2s.c:141:14: note: in expansion of macro ‘sndi2s_FORMATS’
   .formats = sndi2s_FORMATS,
              ^
make[3]: **\* [sound/soc/sunxi/i2s/sndi2s.o] Error 1
make[2]: **\* [sound/soc/sunxi/i2s] Error 2
make[1]: **\* [sound/soc] Error 2
make: **\* [sound] Error 2

**Comment by amery** [comment]
what defconfig did you use? can you diff your current .config with the current equivalent in http://dl.linux-sunxi.org/nightly/linux-sunxi/linux-sunxi-3.4-something/linux-sunxi-3.4-something-latest.config.gz ? (be sure to replace "something" to whatever you used as defconfig)

**Comment by ryba84** [comment]
It works now. I made make mrproper and run build another time and it works on both toolchains. Thanks.
