### ISSUE TITLE
[3.18 / 3.19-rc with DT] no access to nand possible - /dev/nand not available

### ISSUE THREAD

**Issue by crashmaster1** [linux-sunxi/linux-sunxi#227]
Booting from sdcard i wanted to mount the nand partitions but there is no nand device ( /dev/nandx ) available.

I tried it with 3.18.5 and 3.19.rc6 with device trees enabled and the bootup works fine so far.
Could it also be a u-boot problem ?

Thanks, CM.

**Comment by mripard** [comment]
Hi,

The NAND isn't supported so far in the mainline kernels. This is a work in progress, but won't happen before a few more monthes.

Maxime
