### ISSUE TITLE
Usb OTG On SoC A20

### ISSUE THREAD

**Issue by Philippe12** [linux-sunxi/linux-sunxi#233]
Hi

I used a Olinuxino-20-Micro-4Go and i try your kernel for nand driver over mtd, that part work fine (great thank for the working).

But I would like to use the USB otg but it fail (i try branch sunxi-otg-wip, sunxi-wip)
I din't have error in kernel output, musb-hdrc.1.auto is loading without error.
on sunxi-wip branch
If I check extcon class I can see that cable is correctly detected (USB or USB_HOST), but after that nothing and in device mode the host have a error "not enumerate"

thank

**Comment by TsvetanUsunov** [comment]
you should not use work-in-progress kernel!

**Comment by Philippe12** [comment]
Ok

But if I went work with nand support (mdt) and usb OTG witch kernel I must used?

thank

**Comment by Philippe12** [comment]
How can I help you to debug this part?

**Comment by jwrdegoede** [comment]
Hi,

Please send a mail to the linux-sunxi mailinglist about this, that is the preferred way to communicate with the linux-sunxi project. Please also include a link to the git repo + the exact branch you are using.

Regards,

Hans
