### ISSUE TITLE
Problems while playing 1920x1080 videos on mplayer with libvdpau-sunxi

### ISSUE THREAD

**Issue by navjotsingh07** [linux-sunxi/linux-sunxi#266]
Hi
I am working on Olimex A20 Olinuxino-Micro based board and trying to play 1920x1080 video through a serial console command line. I am using mplayer to play the video and debian wheezy 3.4.90+ kernel version; I also installed libvdpau-sunxi and the required libraries, and configured my board to play hardware accelerated videos through cedarx.
The command used to play video is: (Video media info: 20 Mbps, 1920x1080 at 29.970 fps)
**mplayer TestVideo1.mp4**
The mplayer config file is already been updated to:
vo=vdpau,
vc=ffmpeg12vdpau,ffh264vdpau,ffwmv3vdpau,ffvc1vdpau,

**but when I am trying to play the video on my hardware, it shows skipping/jitters in various frames and the playback is not smooth. I am enclosing the link for the video that I tested and shows skipping/jitters.** You can easily observe the skipping/jitters at 6-7th seconds and 12-13th seconds of the video:
Link:
http://sendvid.com/zuarix67 

Can anyone suggest me what could be the possible reason for this behaviour? or is there any other driver or library needs to be installed? I am new to this kind of development, so need a kick start to find my way.
If you need any other information about my build, I can provide that too.

thanks in advance
Nav

**Comment by rellla** [comment]
Nav, this is no linux-sunxi kernel related issue and won't be solved here. Please answer my comment in libvdpau-sunxi issue tracker and provide a log, where the mentioned lines appear. 
rellla
