### ISSUE TITLE
Sun3i clock.c syntaxe error

### ISSUE THREAD

**Issue by sysfwlab** [linux-sunxi/linux-sunxi#27]
Hello all,
I found something seem to be a syntaxe error into a kernel file, i'm not very sure...
(i hope this is the good place to push this issue)
File : /arch/arm/mach-sun3i/clock/clock.c (Line : 1688) - Struct : clk_ahb_de_image0
Field .clk_id is CSP_CCM_MOD_CLK_AHB_DE_IMAGE1 but this must be  CSP_CCM_MOD_CLK_AHB_DE_IMAGE0 no ?
Best regards,
Bin

**Comment by amery** [comment]
what branch are you using? allwinner-v2.6.36-android should give you the "best" results... I didn't know any sun3i device until you mailed the list so I didn't invest time on it... do you have a .config composed for your device?

**Comment by sysfwlab** [comment]
Hy Alexendro, i check before posting, this "probably syntax error" is present on allwinner stock kernel and propaged to all branchs to your last modified 'getioaddr' version. I dont got any .config file for this device, 
When i recover my nanda i come to help you to investigate

**Comment by amery** [comment]
fixed in da7f5e7

**Comment by sysfwlab** [comment]
Many thanks for reactivity
Biin
