### ISSUE TITLE
MAKE FILE ERROR

### ISSUE THREAD

**Issue by sarfaraj118** [linux-sunxi/linux-sunxi#272]
CC user/module.c
CC user/wiopkd.c
AR build/httpd_app.a
GEN ldscript_memspecific.ld
LD build/httpd.out
/home/sarfaraj/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld:ldscript_memspecific.ld:1: warning: redeclaration of memory region irom0_0_seg' /home/sarfaraj/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/httpd.out section.text' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Makefile.combined:22: recipe for target 'build/httpd.out' failed
make: *** [build/httpd.out] Error 1

how can i remove this error i am installed latest toolchain and SDK .could you tell me how remove warning treat as error ?

**Comment by turl** [comment]
That doesn't look like a sunxi kernel build to me. Please report your issue to the correct project.
