### ISSUE TITLE
GC2035 camera driver is unavailable at sunxi-next ?

### ISSUE THREAD

**Issue by informer2016** [linux-sunxi/linux-sunxi#284]
I have Orange PI PC Plus with GC2035 camera module. Upgraded to 4.13.6 sunxi-next mainline kernel and noticed that GC2035 camera driver is gone! Why is it so? Maybe someone forgot to include this driver to the kernel? People are still using these cameras and need them!

If it was a conscious decision to remove the GC2035 camera from the sunxi-next tree - then, well, it was a horrible decision that should be reversed. Please return this driver. https://github.com/avafinger/gc2035

Earlier it was at `./drivers/media/video/sunxi-vfe/device/gc2035.c` location, but now the directory structure could be very different...

**Comment by wens** [comment]
sunxi-next is an integration testing branch for the mainline kernel.
The mainline kernel does not have a driver for GC2035.
