### ISSUE TITLE
Kernel doesn't boot / or output anything to uSD UART

### ISSUE THREAD

**Issue by zenitraM** [linux-sunxi/linux-sunxi#3]
Booting on my Novo7 Advanced, from u-boot:

```
Q2011.09-rc1 (Feb 28 2012 - 15:54:51) Allwinner Technology

CPU:   SUNXI Family
Board: A10-EVB
DRAM:  512 MiB
NAND:  3504 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
--------fastboot partitions--------
-total partitions:8-
-name-        -start-       -size-
BOOTFS      : 100000        1000000
LROOTFS     : 1100000       2000000
LSYSTEMFS   : 3100000       10000000
LDATAFS     : 13100000      40000000
MISC        : 53100000      100000
LRECOVERYFS : 53200000      2000000
LCACHEFS    : 55200000      10000000
UDISK       : 65200000      75e00000
-----------------------------------
Hit any key to stop autoboot:  0
sun4i#help
?       - alias for 'help'
base    - print or set address offset
boot    - boot default, i.e., run 'bootcmd'
boota   - boota   - boot android bootimg from memory

bootd   - boot default, i.e., run 'bootcmd'
bootm   - boot application image from memory
cmp     - memory compare
cp      - memory copy
crc32   - checksum calculation
env     - environment handling commands
exit    - exit script
false   - do nothing, unsuccessfully
fastboot- fastboot- use USB Fastboot protocol

fatdown - download data to a dos filesystem
fatinfo - print information about filesystem
fatload - load binary file from a dos filesystem
fatls   - list files in a directory (default /)
go      - start application at address 'addr'
help    - print command description/usage
key_test- Test the key value and dump key registers
loop    - infinite loop on address range
md      - memory display
mm      - memory modify (auto-incrementing address)
mtest   - simple RAM read/write test
mw      - memory write (fill)
nand    - NAND sub-system
nboot   - boot from NAND device
nm      - memory modify (constant address)
printenv- print environment variables
reset   - Perform RESET of the CPU
run     - run commands in an environment variable
saveenv - save environment variables to persistent storage
setenv  - set environment variables
showvar - print local hushshell variables
test    - minimal test like /bin/sh
true    - do nothing, successfully
version - print monitor, compiler and linker version
sun4i#fatls nand 7
            lost.dir/
            .android_secure/
  3632540   uimage
    40692   sys_config1.bin
            android/

2 file(s), 3 dir(s)

sun4i#fatload nand 7 50000000 uimage
reading uimage

3632540 bytes read
sun4i#bootm 50000000
## Booting kernel from Legacy Image at 50000000 ...
   Image Name:   Linux-3.0.8-android+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3632476 Bytes = 3.5 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK

Starting kernel ...
```

And from there, silence.

The kernel is either not booting, or booting and not outputting anything, or booting and outputting anywhere else (I'm debugging using the uSD breakout).

**Comment by hipboi** [comment]
Hi,
   Is there a script.bin in your nanda ? Is the script.bin uart output or
Sd card output? Script.bin is loaded to ram 0x43000000 address before
U-boot running by boot1.

Besides, you can reload the sys_config1.bin to 0x43000000 to override the
One loaded by boot1before in u-boot then loads the kernel.

sun4i#fatload nand 7 43000000 sys_config1.bin

sun4i#fatload nand 7 50000000 uimage

sun4i#bootm 50000000

On Sunday, March 4, 2012, zenitraM <
reply@reply.github.com>
wrote:

> Booting on my Novo7 Advanced, from u-boot:
> 
> ```
> Q2011.09-rc1 (Feb 28 2012 - 15:54:51) Allwinner Technology
> 
> CPU:   SUNXI Family
> Board: A10-EVB
> DRAM:  512 MiB
> NAND:  3504 MiB
> *** Warning - bad CRC, using default environment
> 
> In:    serial
> Out:   serial
> Err:   serial
> --------fastboot partitions--------
> -total partitions:8-
> -name-        -start-       -size-
> BOOTFS      : 100000        1000000
> LROOTFS     : 1100000       2000000
> LSYSTEMFS   : 3100000       10000000
> LDATAFS     : 13100000      40000000
> MISC        : 53100000      100000
> LRECOVERYFS : 53200000      2000000
> LCACHEFS    : 55200000      10000000
> UDISK       : 65200000      75e00000
> -----------------------------------
> Hit any key to stop autoboot:  0
> sun4i#help
> ?       - alias for 'help'
> base    - print or set address offset
> boot    - boot default, i.e., run 'bootcmd'
> boota   - boota   - boot android bootimg from memory
> 
> bootd   - boot default, i.e., run 'bootcmd'
> bootm   - boot application image from memory
> cmp     - memory compare
> cp      - memory copy
> crc32   - checksum calculation
> env     - environment handling commands
> exit    - exit script
> false   - do nothing, unsuccessfully
> fastboot- fastboot- use USB Fastboot protocol
> 
> fatdown - download data to a dos filesystem
> fatinfo - print information about filesystem
> fatload - load binary file from a dos filesystem
> fatls   - list files in a directory (default /)
> go      - start application at address 'addr'
> help    - print command description/usage
> key_test- Test the key value and dump key registers
> loop    - infinite loop on address range
> md      - memory display
> mm      - memory modify (auto-incrementing address)
> mtest   - simple RAM read/write test
> mw      - memory write (fill)
> nand    - NAND sub-system
> nboot   - boot from NAND device
> nm      - memory modify (constant address)
> printenv- print environment variables
> reset   - Perform RESET of the CPU
> run     - run commands in an environment variable
> saveenv - save environment variables to persistent storage
> setenv  - set environment variables
> showvar - print local hushshell variables
> test    - minimal test like /bin/sh
> true    - do nothing, successfully
> version - print monitor, compiler and linker version
> sun4i#fatls nand 7
>            lost.dir/
>            .android_secure/
>  3632540   uimage
>    40692   sys_config1.bin
>            android/
> 
> 2 file(s), 3 dir(s)
> 
> sun4i#fatload nand 7 50000000 uimage
> reading uimage
> 
> 3632540 bytes read
> sun4i#bootm 50000000
> ## Booting kernel from Legacy Image at 50000000 ...
>   Image Name:   Linux-3.0.8-android+
>   Image Type:   ARM Linux Kernel Image (uncompressed)
>   Data Size:    3632476 Bytes = 3.5 MiB
>   Load Address: 40008000
>   Entry Point:  40008000
>   Verifying Checksum ... OK
>   Loading Kernel Image ... OK
> OK
> 
> Starting kernel ...
> ```
> 
> And from there, silence.
> 
> The kernel is either not booting, or booting and not outputting anything,
> or booting and outputting anywhere else (I'm debugging using the uSD
> breakout).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amery/linux-allwinner/issues/3

## 

Keep simple, stay foolish.

**Comment by zenitraM** [comment]
There is, it is configured to output to uSD.

I'm running u-boot from boot1's recovery (as on: http://elinux.org/Hack_A10_devices). Booting normally the Android 2.6.36 firm on the kernel outputs to uSD correctly, and also loading the 2.6.36 kernel from allwinner repo works:

```
sun4i#fatload nand 7 50000000 lin/uImage
reading lin/uImage

3824552 bytes read
sun4i#bootm 50000000
## Booting kernel from Legacy Image at 50000000 ...
   Image Name:   Linux-2.6.36-android
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3824488 Bytes = 3.6 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK

Starting kernel ...

[    0.000000] Ignoring unrecognised tag 0x00000000
[    2.020000] Gadget Android: controller 'sw_usb_udc' not recognized
[    2.030000] ps2: cannot find any unsing configuration for 2 ps/2 controller, return directly!
[    2.070000] audiocodec_adap_awxx_init: script_parser_fetch err.
[    2.070000] No device for DAI sun4i-hdmiaudio
(....)
```

Loading the script.bin to that address makes no difference. I think it is loaded by boot1:

```
# cat linux/recovery.ini
[segment]
img_name = c:\linux\u-boot.bin
img_size = 0x80000
img_base = 0x4A000000

[segment]
img_name = c:\linux\paramsr
img_size = 0x100
img_base = 0x40000100

[script_info]
script_base = 0x43000000
script_size = 0x10000

[logo_info]
logo_name = c:\linux\android.bmp
logo_address = 0x48000000
logo_show = 1
```

**Comment by amery** [comment]
It's worth noting he is testing the allwinner-v3.0-android branch.

please check you have early printk enabled and the right debug uart set

**Comment by zenitraM** [comment]
CONFIG_EARLY_PRINTK is enabled
using UART0

**Comment by hno** [comment]
For early printk to actually output anything you also need to provide the earlyprintk kernel boot argument.

**Comment by hno** [comment]
What does c:\linux\paramsr contain? This smells like a kernel boot parameters record.

**Comment by amery** [comment]
those printk messages seem to come from initrd, so the kernel is booting... but quitely :-/

if in the defconfig of `allwinner-v3.0-android` you disable `CONFIG_VIDEO_CSI_SUN4I` and `CONFIG_SND_SOC` you can build both the uImage and modules without troubles... I haven't looked inside Allwinner's build scripts but having the modules probably helps initrd to bring more of the system up.

also, not sure if it's related but there is a change form the 2.6.36 patch that alter default loglevel filters. https://github.com/amery/linux-allwinner/commit/28aea0dea5d1d374b2e59d6338113a8039e56144#diff-22

**Comment by zenitraM** [comment]
paramsr contains the boot parameters for Linux if loading Linux - but I'm booting u-boot so it shouldn't matter, I think..

The modules aren't required AFAIK, at least the 2.6.36 kernel can get to boot without finding them.

The 2.6.36 boots quietly too, the boot_args are something like:
root=/dev/nandd console=ttyS0,115200 rw init=/init mem=448M@0x40000000 fbmem=32M@0x5a000000 loglevel=8;

so I don't know why are both kernels booting quietly....

I'm using a modified u-boot that outputs to the uSD following some instructions that hipboi told me at IRC

**Comment by hipboi** [comment]
```
sun4i#fatload nand 7 50000000 lin/uImage
reading lin/uImage

3824552 bytes read
sun4i#bootm 50000000
## Booting kernel from Legacy Image at 50000000 ...
   Image Name:   Linux-2.6.36-android
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    3824488 Bytes = 3.6 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK

Starting kernel ...

[    0.000000] Ignoring unrecognised tag 0x00000000
[    2.020000] Gadget Android: controller 'sw_usb_udc' not recognized
[    2.030000] ps2: cannot find any unsing configuration for 2 ps/2 controller, return directly!
[    2.070000] audiocodec_adap_awxx_init: script_parser_fetch err.
[    2.070000] No device for DAI sun4i-hdmiaudio
(....)
```

These are printed by kernel, maybe the loglevel is not high, only warnning and error messages are printed.

**Comment by hipboi** [comment]
The linux kernel repo from amery is a little bit older than the "allwinner official repo". In amery's repo the kernel get the boot params from a dram address which boot1 load a string to it, the string is from c:\linux\params. But we fixed this when we use u-boot to load the kernel, take a look at this commit.

https://github.com/allwinner/linux-2.6.36/commit/fa4bab26f02291bd13dc5536bf9a074a1f776c3a

**Comment by hno** [comment]
sön 2012-03-04 klockan 18:23 -0800 skrev Tom Cubie:

> The linux kernel repo from amery is a little bit older than the
> "allwinner official repo". In amery's repo the kernel get the boot
> params from a dram address which boot1 load a string to it, the string
> is from c:\linux\params. But we fixed this when we use u-boot to load
> the kernel, take a look at this commit.
> 
> https://github.com/allwinner/linux-2.6.36/commit/fa4bab26f02291bd13dc5536bf9a074a1f776c3a

Do you mean this?
-       .boot_params    = (unsigned long)(0x40000000 + 0x100),
-       .boot_params    = (unsigned long)(0x40000000 + 0x400),

Regards
Henrik

**Comment by hipboi** [comment]
no, i mean the one which modified the kernel start up code and
disable the kernel TAG params parsing commit.

The modify of the address is for compatible with the boot1,
boot1 load the kernel cmd string to 0x40000100 so the u-boot
has to load the TAG params to somewhere else that is 0x40000400.

2012/3/5 Henrik Nordstrm <
reply@reply.github.com

> sn 2012-03-04 klockan 18:23 -0800 skrev Tom Cubie:
> 
> > The linux kernel repo from amery is a little bit older than the
> > "allwinner official repo". In amery's repo the kernel get the boot
> > params from a dram address which boot1 load a string to it, the string
> > is from c:\linux\params. But we fixed this when we use u-boot to load
> > the kernel, take a look at this commit.
> > 
> > https://github.com/allwinner/linux-2.6.36/commit/fa4bab26f02291bd13dc5536bf9a074a1f776c3a
> 
> Do you mean this?
> -       .boot_params    = (unsigned long)(0x40000000 + 0x100),
> -       .boot_params    = (unsigned long)(0x40000000 + 0x400),
> 
> Regards
> Henrik
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amery/linux-allwinner/issues/3#issuecomment-4316070

## 

Keep simple, stay foolish.

**Comment by hno** [comment]
sön 2012-03-04 klockan 19:14 -0800 skrev Tom Cubie:

> no, i mean the one which modified the kernel start up code and
> disable the kernel TAG params parsing commit.

Looks to me as if all of the changes in setup.c is already in the tree.

> The modify of the address is for compatible with the boot1,
> boot1 load the kernel cmd string to 0x40000100 so the u-boot
> has to load the TAG params to somewhere else that is 0x40000400.

Only the address change was not already in amery kernel tree from what I
can tell.

Why can't u-boot load boot_params at the same place as boot1 does? Is
this to keep compatibility with old style even when loaded via u-boot
chain-loaded from boot1?

Regards
Henrik

**Comment by hipboi** [comment]
> Why can't u-boot load boot_params at the same place as boot1 does? Is
> this to keep compatibility with old style even when loaded via u-boot
> chain-loaded from boot1?

yes

In current u-boot code the params address is 0x40000100, the code is here

http://git.hands.com/?p=u-boot.git;a=blob;f=board/allwinner/a10-evb/a10-evb.c;h=b1db2ffe28549556e1053527506931a87705cf88;hb=lichee-dev-mmc

**Comment by amery** [comment]
for the records, the change moving the boot_params to `0x40000400` (allwinner/linux-2.6.36@fa4bab26f02291bd13dc5536bf9a074a1f776c3a) was reverted by @hipboi in allwinner/linux-2.6.36@df20dc2b77210f82276807506fdb4da8ca04e63e a week later.

If you find any other change not present in `allwinner-v3.0-android` please reopen #4

**Comment by zenitraM** [comment]
The last source is still quiet for me. Creating the bImage by using:

```
${OBJCOPY} -R .note.gnu.build-id -S -O binary vmlinux output/bImage
```

and booting the bImage from Boot1 (to avoid any u-boot bootargs problem) by replacing the old one, the kernel is still quiet. With the same kernel args, the original kernel (2.6.36) booted, non-silently.

**Comment by amery** [comment]
after quite a bunch of experimentation my conclusions are that to boot from uSD using @hipboi's [u-boot/lichee-dev-mmc](https://github.com/amery/uboot-allwinner/commits/lichee-dev-mmc)  branch and actually _see_ kernel output it's required to load script.bin using this in the `u-boot` script.

```
fatload mmc 0 0x43000000 script.bin
```

but before actually been able to boot these kernels we need to rework 9aae53f907709010497ac6db7338786cb0c1fbe6 (see #1) into something less hackish we can carry. ... _help wanted_

**Comment by zenitraM** [comment]
I tested the kernel with a chainloaded u-boot from boot1 so script.bin was probably already being loaded by boot1...

**Comment by hipboi** [comment]
How about load the script.bin to the high address of ram, like the end 4M
of the ram
and pass the boot params of mem=508M@0x40000000 to kernel.

On Wed, Mar 28, 2012 at 9:50 PM, zenitraM <
reply@reply.github.com

> wrote:
> 
> I tested the kernel with a chainloaded u-boot from boot1 so script.bin was
> probably already being loaded by boot1...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amery/linux-allwinner/issues/3#issuecomment-4765107

## 

Keep simple, stay foolish.

**Comment by jmchen75** [comment]
I met the same problem. I use MeleA1000 ipbox. The kernel can not output anything, and die.

**Comment by amery** [comment]
@jmchen75: this problem is supposed to be gone. what exactly are you building and how? and what bootloader?

**Comment by jmchen75** [comment]
I use allwinner/lichen-v2.6.36 to build with suni4_crane_defconfg, and open the early printk. Also,I tried other branches. All result is the same. Kernel can not run at all. In mele a1000, it is already use boot+uboot, then uboot setup bootargs, load uImage to run. Bootargs can be used by the original kernel. Uart output is ok and loglevel is 8. Script.bin seems not affect it. I try to use other script.bin, it will make original kernel load sata module failed. My custom kernel is still dead.

**Comment by amery** [comment]
@jmchen75 `allwinner-v2.6.36-android` booted fine the last time I tried, but that branch doesn't receive any work. be sure to load script.bin properly, and don't use one from different devices.

**Comment by jmchen75** [comment]
Yes. I know the script.bin is used to configure pinmux. I use md command of uboot to display 43000000. It is correct. What is your platform? Nano7?Or allwinner's devboard? The A1000 has 512MB memory. How many memory your platform have? Maybe the stack is out of memory?

**Comment by amery** [comment]
@jmchen75 I use a mele a1000 as devkit, but please move that discussion to the mailing list.

**Comment by jmchen75** [comment]
what mailing list? I'm new guy for github

**Comment by gaara87** [comment]
@jmchen75  http://lists.phcomp.co.uk/mailman/listinfo/arm-netbook

**Comment by jmchen75** [comment]
@nutrixtech It's cool! Thanx
