### ISSUE TITLE
others' copyright notice need to be kept

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/linux-sunxi#35]
https://github.com/amery/linux-allwinner/commit/28e7824ca18954ea029747857cb05b1619934949#diff-1
(I just saw this change but I didn't see all license updates yet. I'll see other updates later)

**Comment by hipboi** [comment]
it takes time, i will handle others in the future.

**Comment by hno** [comment]
Looks to me like the original copyright attribution in sw_ahci_platform.h was a copy-paste error. I don't find anything in that file not of Allwinner origin.

but sw_ahci_platform.c seems to be based on ahci_platform.c and should have proper copyright attributions added. This may be true for a number of other drivers as well.

**Comment by hno** [comment]
sw_ahci_platform.c copyright updated to include original copyright from ahci_platform.c.

**Comment by hipboi** [comment]
thanks, hno
