### ISSUE TITLE
Display won't wake up after suspend

### ISSUE THREAD

**Issue by Quarx2k** [linux-sunxi/linux-sunxi#38]
On first boot the display is works. After suspend display won't wake up (only backlight), touchscreen works on black screen. HDMI works after sleep, wake up without problem.
This problem only for Ainol Novo 7 Aurora (not see this problem on any other a10-based device)
No errors in dmesg,
Resolve the  problem: https://github.com/Quarx2k/linux-allwinner/commit/31974a21c503aa5e0767dc4c28f009a39819e6dc
But it cause very big battery drain in idle mode.

**New info**: Aurora use SPI interface module. In current kernel tree missing drivers for spi.
If i disable the "cd_spi_para", display can't wakeup on ainol kernel too.
https://gist.github.com/2979796

**Comment by killerkink** [comment]
This happened to p76ti as well. Even the 3.0.8 branch. But in the case of p76ti, going to sleep cause tablet to reboot.

Allwinner Qware 3.0.8 source work without issue.

**Comment by Quarx2k** [comment]
At night in idle - battery drop from 100% to 48%.. is not good:(
Allwinner Qware 3.0.8  don't works too
Ok, found new fix.  ticket updated.

**Comment by amery** [comment]
I've ported a patch from allwinner to our 3.0-v2 (6c01b6c84fff553672dc4c098eb62161e64597c7) which doesn't only include lcd_spi but also a bunch of improvements in other areas of disp. it would be awesome if you could test it.

**Comment by Quarx2k** [comment]
No problems, i set:
CONFIG_LYCHEE_FB_SUN4I=y
CONFIG_LYCHEE_LCD_SUN4I=y
CONFIG_LYCHEE_LCD_AINOL_AUROTA=y
CONFIG_LYCHEE_HDMI_SUN4I=y

And please rename AUROTA to AURORA :)

Problem: HDMI is green display... Photo: http://quarx2k.ru/.temp/IMG_20120705_141842.jpg
Explanation: By default now HDMI Display mode: YUV, by switch to RGB(on monitor), picture is correct.

**Comment by amery** [comment]
should we find a way to change that default somehow back to RGB or YUV is fine?

**Comment by Quarx2k** [comment]
we should find way to change back to RGB.
Because YUV is green :p
+//out_csc: 0:rgb, 1:yuv for tv, 2:yuv for hdmi
+//out_color_range:  0:16~255, 1:0~255, 2:16~235

**Comment by amery** [comment]
https://github.com/amery/linux-allwinner/commit/6c01b6c84fff553672dc4c098eb62161e64597c7#L1R189 sets the TV type to YUV, not the HDMI....

**Comment by Quarx2k** [comment]
I tried to set out_csc =1 for HDMI, colors now looks badly than with 0.
Maybe problem with out_color_range

**Comment by amery** [comment]
0a3d1af067f5428c897e5423ccfef8f6c25456ec added lcd_spi support, while the part that causes this green hdmi output effect has been moved for future research into the `wip/linux-sunxi-3.0/disp` branch.
