### ISSUE TITLE
"ksoftirqd/0" always use 3-8% CPU.

### ISSUE THREAD

**Issue by Quarx2k** [linux-sunxi/linux-sunxi#43]
It happening because HDMI is waiting connect for cable. Checking it every 200ms (in sleep too).
Simply solution to increase hdmi_delay_ms for 2sec  - "drivers/video/sun4i/hdmi/drv_hdmi.c"
After ksoftirqd/0  always 0%.

**Comment by amery** [comment]
isn't this kind of too long?

**Comment by Quarx2k** [comment]
I'm not tested <15 sec. 
But 15sec is no problem to use hdmi. After connect cable we should wait <15sec.

**Comment by killerkink** [comment]
isnt the original delay set at 200ms?

hdmi_delay_ms(200); @ drv_hdmi.c

**Comment by Quarx2k** [comment]
Yes, you right. Then better to increase hdmi_delay_ms.  And make suspend for it.

**Comment by killerkink** [comment]
i have tesed 1sec with good response. but I believe 2 sec is reasonable for cutting down on the polling and getting a good detection.

**Comment by hipboi** [comment]
thanks @Quarx2k for the fix. This is a long issue of Allwinner. I looked at this today. Another way to fix is to change in drivers/video/sun4i/hdmi/aw/hdmi_core.c function __s32 main_Hpd_Check(void); change the hdmi_delay_ms(1) to hdmi_delay_ms(10). i can not explain it with my current understanding of the kernel schedule. can anyone explain this?

**Comment by polarcat** [comment]
I think that we could simply replace hdmi_delay_ms() with msleep(). Please correct me if I am wrong.

**Comment by hipboi** [comment]
On Tue, Sep 11, 2012 at 6:19 PM, Aliaksei Katovich <notifications@github.com

> wrote:
> 
> I think that we could simply replace hdmi_delay_ms() with msleep(). Please
> correct me if I am wrong.
> 
> yes, that also works. can anyone explain this?
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/43#issuecomment-8455122.

## 

Keep simple, stay foolish.

**Comment by polarcat** [comment]
does msleep(1) produce the same effect as hdmi_delay_ms(1)?

**Comment by hipboi** [comment]
On Tue, Sep 11, 2012 at 6:46 PM, Aliaksei Katovich <notifications@github.com

> wrote:
> 
> does msleep(1) produce the same effect as hdmi_delay_ms(1)?
> 
> no. hdmi_delay_ms uses set_current_state(TASK_INTERRUPTIBLE), but msleep
> uses schedule_timeout_uninterruptible(timeout). Interesting, i need to
> google the difference between TASK_INTERRUPTIBLE and TASK_UNINTERRUPTIBLE.
> but from hardware point of view, they are the same, wait for some time, and
> check again.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/43#issuecomment-8455695.

## 

Keep simple, stay foolish.

**Comment by polarcat** [comment]
>    On Tue, Sep 11, 2012 at 6:46 PM, Aliaksei Katovich
>    <notifications@github.com
> 
> > wrote:
> > does msleep(1) produce the same effect as hdmi_delay_ms(1)?
> > 
> >    no. hdmi_delay_ms uses set_current_state(TASK_INTERRUPTIBLE), but
> >    msleep
> >    uses schedule_timeout_uninterruptible(timeout). Interesting, i need to
> >    google the difference between TASK_INTERRUPTIBLE and
> >    TASK_UNINTERRUPTIBLE.
> >    but from hardware point of view, they are the same, wait for some time,
> >    and
> >    check again.

```
I would anyway recommend to use plain msleep() here, regardless of your
findings. E.g. jiffies calculations like this (see. hdmi_delay_ms)

    __u32 timeout = t*HZ/1000

look suspicious to me.
```
