### ISSUE TITLE
Please support RAM Console

### ISSUE THREAD

**Issue by turl** [linux-sunxi/linux-sunxi#45]
RAM Console is a handy way to keep a copy of the kernel log across a reboot. It's really useful to catch unexpected reboots and kernel panics

Patch: https://github.com/allwinner-dev-team/linux-allwinner/commit/3f3f02200f6cf63f47147150ae99825b4b6f7598.patch

```
wget -O- https://github.com/allwinner-dev-team/linux-allwinner/commit/3f3f02200f6cf63f47147150ae99825b4b6f7598.patch | git am
```

**Comment by amery** [comment]
thanks, applied as 21da915c911ad4f0763b0c45e2c43667bfa6245a
