### ISSUE TITLE
pendings porting to 3.4

### ISSUE THREAD

**Issue by amery** [linux-sunxi/linux-sunxi#48]
drivers that got broken:
- drivers/net/wireless/rtl8192cu/ → allwinnerized version of drivers/net/wireless/rtlwifi/rtl8192cu

pending merges:
- ~~mali integration → `wip/linux-3.4-sunxi/mali` branch~~
- RAM Console (21da915c911ad4f0763b0c45e2c43667bfa6245a)
- smartass v2 governor (67aaa26dab7f7345864e774ffc3be382218f1090)
- core changes in @hno's tree https://github.com/hno/linux-allwinner/commits/linux-sun4i-minimal
- #28
- #29

pending merges not even in 3.0-v2 tree:
- https://github.com/amery/linux-allwinner/tree/wip/lichee3-sunxi/import-sun5i
- lcd_spi https://github.com/amery/linux-allwinner/commits/wip/linux-sunxi-3.0/lcd_spi

**Comment by amery** [comment]
mali merged

**Comment by wingrime** [comment]
amery please update issue
