### ISSUE TITLE
eth0 link always down

### ISSUE THREAD

**Issue by davidgiven** [linux-sunxi/linux-sunxi#49]
When using sun4i_defconfig on branch allwinner-v3.0-android-v2, on a Mele A1000, the ethernet driver will sometimes refuse to see that the cable is plugged in. When the interface is brought up, I get:

<7>wemac wemac.0: enabling eth0
<4>wemac wemac.0: WARNING: no IRQ resource flags set.
<7>wemac wemac.0: resetting device
<6>wemac wemac.0: eth0: link down

This varies from build to build of the kernel, but once I have a kernel where the interface doesn't come up, it never comes up from that kernel. This happens on a completely stock sun4i_defconfig kernel with no modules loaded.

The interface's MAC address is being configured via a uboot variable. My /etc/network/interfaces is minimal:

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
```

Watching the link light on the interface, I see:
- light on during uboot.
- light goes out sometime during boot.
- if working: light goes on when interface is brought up, otherwise the light stays off.

It's been doing this for a while but I've only just had time to look into it. This disturbs me a little because if this is as common as I've been observing, surely someone else would have observed it too.

I'm using the standard emdebian gcc toolchain, 4.4.5-8; is it worth trying a different compiler?

**Comment by hno** [comment]
tis 2012-07-03 klockan 13:32 -0700 skrev David Given:

> This varies from build to build of the kernel, but once I have a
> kernel where the interface doesn't come up, it never comes up from
> that kernel. This happens on a completely stock sun4i_defconfig kernel
> with no modules loaded.

Ok. Sounds as there may be some uninitialized variable in the wemac
driver.

Regards
Henrik

**Comment by davidgiven** [comment]
I have faint memories of noticing that (when it works) the activity light is sometimes on, blinking off for activity, and sometimes off, blinking on. But I couldn't put money on it.

Assuming this is a plausible bug and not something wrong with my setup, anything you want me to look at?

**Comment by suzuke** [comment]
I confirm this issue.

**Comment by suzuke** [comment]
This is part of boot log.

```
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<7>wemac wemac.0: RX: Bad Packet (runt)
<6>wemac wemac.0: eth0: link down
<7>eth0: no IPv6 routers present
```

It seems something wrong with wemac.

**Comment by davidgiven** [comment]
I've just rebuilt with the 4.3 compiler and can confirm this is still present there.

I'm curious about that IRQ warning. When I do ifconfig eth0 on the (non-working) interface, I get this:

```
      Interrupt:55 Base address:0x6000 
```

Is this correct? What are other people seeing?

**Comment by davidgiven** [comment]
I've finally seen the wireless come up (purely coincidentally, I was doing something else):

<7>wemac wemac.0: enabling eth0
<4>wemac wemac.0: WARNING: no IRQ resource flags set.
<7>wemac wemac.0: resetting device
<6>wemac wemac.0: eth0: link down
<6>ADDRCONF(NETDEV_UP): eth0: link is not ready  
Listening on LPF/eth0/00:ce:39:b6:63:ec
Sending on   LPF/eth0/00:ce:39:b6:63:ec
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 4
<6>wemac wemac.0: eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
<6>ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 6
DHCPREQUEST on eth0 to 255.255.255.255 port 67
DHCPOFFER from 10.0.0.1
DHCPACK from 10.0.0.1

ifconfig eth0 shows:

```
Interrupt:55 Base address:0xa000 
```

I know absolutely nothing about the hardware, but in the non-working case I saw above the base address was 0x6000...

**Comment by davidgiven** [comment]
For reference, the detailed /proc/iomem entries for the working wemac are:

```
01c00000-01c00400 : wemac.0
01c0b000-01c0b400 : wemac.0
  01c0b000-01c0b400 : wemac
01c20000-01c20400 : wemac.0
01c20800-01c20c00 : wemac.0
```

**Comment by Vayu** [comment]
You can try to enable extra debug messages in the driver with:
# ethtool -s eth0 msglvl 0xffff

And then try ifdown eth0 and ifup eth0.

**Comment by davidgiven** [comment]
I finally managed to compare working and non-working side by side.

The non-working /proc/iomem is identical to the one posted above. The ethtool output isn't that interesting:

Working:

```
<7>wemac wemac.0: enabling eth0
<4>wemac wemac.0: WARNING: no IRQ resource flags set.
<7>wemac wemac.0: resetting device
<6>wemac wemac.0: eth0: link down
<6>ADDRCONF(NETDEV_UP): eth0: link is not ready
<6>wemac wemac.0: eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
<6>ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
<7>wemac wemac.0: emac interrupt 01
...etc...
```

Non-working:

```
<7>wemac wemac.0: enabling eth0
<4>wemac wemac.0: WARNING: no IRQ resource flags set.
<7>wemac wemac.0: resetting device
<6>wemac wemac.0: eth0: link down
<6>ADDRCONF(NETDEV_UP): eth0: link is not ready
(no more tracing)
```

And that's it.

**Comment by amery** [comment]
do you still have this problem?

**Comment by davidgiven** [comment]
I have not seen this happen since the fixes described on #46, so I suspect that it's fixed, so closing (I can always resubmit if it comes back).

**Comment by zioproto** [comment]
Hello,
I have also this issue :(
I am using the current sunxi-3.4 kernel branch.
Is there any stable version that gets rid of this problem ?

**Comment by hno** [comment]
fre 2013-05-17 klockan 14:35 -0700 skrev Saverio Proto:

> Hello,
> I have also this issue :(
> I am using the current sunxi-3.4 kernel branch.

What board and script.bin do you have?

Regards
Henrik

**Comment by zioproto** [comment]
Hello,
I have a cubieboard.
I compiled my self the script.bin for the cubieboard using the instructions here:
http://linux-sunxi.org/FirstSteps

However the LEDs of the Ethernet port are always off, even if I boot with the default operating system in the Nand. I think I have an hardware fault and not a software bug.

Is your ethernet port working if you boot with the default operating system from nand ? do you have cubieboard also ?

**Comment by hno** [comment]
lör 2013-05-18 klockan 00:06 -0700 skrev Saverio Proto:

> Is your ethernet port working if you boot with the default operating
> system from nand ? do you have cubieboard also ?

I have a cubieboard but not the Anroid os.

I have verified that the Ethernet do work fine from u-boot however.

The ethernet leds should go on as soon as you connect a cable, even if
nothing is running on the board, at least assuming the Ethernet PHY
power control have not been enabled. The schematics supports powering
off the ethernet PHY, but it is hardwired on in the board I have and I
have not heard of any changes in this.

Regards
Henrik
