### ISSUE TITLE
Hardware performance counters do not work (perf, oprofile)

### ISSUE THREAD

**Issue by Vayu** [linux-sunxi/linux-sunxi#53]
Running oprofile or perf fails to collect any events from ARM hardware performance counters. The system log shows:
[46554.550000] oprofile: using arm/armv7
[46679.440000] hw perfevents: unable to reserve pmu

Brief googling shows that there was similar problem with OMAP CPUs and there is a patch available for them. It might be possible to adapt it.

**Comment by amery** [comment]
for the records, what branch did you use?

**Comment by Vayu** [comment]
I'm using allwinner-v3.0-android-v2. As I understand (correct me if I'm wrong) it is the most feature rich and stable branch at the moment.

**Comment by ssvb** [comment]
I have tried to take PMU IRQ into use https://gist.github.com/4515166

And now at least "perf stat <some_command_to_run>" works and shows the performance counter values. However it does not seem like any IRQs are actually generated when doing profiling in statistical sampling mode. Is the nPMUIRQ pin even connected?

**Comment by ssvb** [comment]
After a discussion with @techn on IRC, we figured out that this proposed fix was just missing the right IRQ number (SW_INT_IRQNO_PLE_PFM instead of SW_INT_IRQNO_PMU). The updated patch has been submitted here: https://groups.google.com/forum/#!topic/linux-sunxi/8guu3f_e-h4

**Comment by amery** [comment]
thank you! applied to both stage branches. (also for sun5i)

**Comment by turl** [comment]
Is this still an issue?

**Comment by ssvb** [comment]
Everything works fine for me. I guess we can close this bug and let @Vayu reopen it if anything is still wrong.
