### ISSUE TITLE
Sir Im Not able to compile this kernel for sun4i ( all winner 10 ) 

### ISSUE THREAD

**Issue by keyur2maru** [linux-sunxi/linux-sunxi#54]
Sir Can u help Im developer and im trying to compile with this kernel source for sun4i ( all winner 10 ) tablets but im getting compilation error i  did def config for my device and set the tool chain path but i m getting error on compilation can u help me 
here is log : 

rom@rom-laptop:~$ cd kernel
rom@rom-laptop:~/kernel$ cd funbook_kernel
rom@rom-laptop:~/kernel/funbook_kernel$ cd kernel
rom@rom-laptop:~/kernel/funbook_kernel/kernel$ make sun4i_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/lex.zconf.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
# 
# configuration written to .config
# 

rom@rom-laptop:~/kernel/funbook_kernel/kernel$ make -j3
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/linux/version.h
  UPD     include/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  HOSTCC  scripts/genksyms/genksyms.o
  SHIPPED scripts/genksyms/lex.c
  SHIPPED scripts/genksyms/parse.h
  CC      scripts/mod/empty.o
cc1: error: unrecognized command line option "-m64"
cc1: error: unrecognized command line option "-mno-red-zone"
cc1: error: unrecognized command line option "-mcmodel=kernel"
cc1: error: unrecognized command line option "-maccumulate-outgoing-args"
make[2]: **\* [scripts/mod/empty.o] Error 1
make[1]: **\* [scripts/mod] Error 2
make[1]: **\* Waiting for unfinished jobs....
  SHIPPED scripts/genksyms/keywords.c
  SHIPPED scripts/genksyms/parse.c
  CC      kernel/bounds.s
cc1: error: unrecognized command line option "-m64"
cc1: error: unrecognized command line option "-mno-red-zone"
cc1: error: unrecognized command line option "-mcmodel=kernel"
cc1: error: unrecognized command line option "-maccumulate-outgoing-args"
make[1]: **\* [kernel/bounds.s] Error 1
make: **\* [prepare0] Error 2
make: **\* Waiting for unfinished jobs....
  HOSTCC  scripts/genksyms/lex.o
  HOSTCC  scripts/genksyms/parse.o
  HOSTLD  scripts/genksyms/genksyms
make: **\* [scripts] Error 2
rom@rom-laptop:~/kernel/funbook_kernel/kernel$ 

plz help me :) hope i get help

**Comment by amery** [comment]
you need to use a proper cross compiler. see https://github.com/amery/linux-allwinner/wiki/Building as a quick hint.

**Comment by keyur2maru** [comment]
Sir @amery  From where can i get this toolchain :D plz help
