### ISSUE TITLE
fbcon and mali seem to cause crash if both loaded

### ISSUE THREAD

**Issue by TJC** [linux-sunxi/linux-sunxi#56]
I'm currently at commit 23e5456879 in the allwinner-v3.0-android-v2 branch.

If I attempt to load the various Mali display modules, as well as fbcon for the console, then the modprobe on fbcon hangs for a long time, then my device crashes.

Apologies for the brevity of this error report -- I do not have a current way to capture any kernel panics as my device is headless and had not written it to syslog.

Note that everything was being loaded as modules, not compiled into kernel.

**Comment by amery** [comment]
unfortunatelly fbcon is not supported

**Comment by amery** [comment]
see #6

**Comment by TJC** [comment]
Ah, my apologies.

**Comment by hno** [comment]
ons 2012-07-18 klockan 22:09 -0700 skrev Toby Corkindale:

> If I attempt to load the various Mali display modules, as well as fbcon for the console, then the modprobe on fbcon hangs for a long time, then my device crashes.

fbcon is known to be broken with the sunxi disp framebuffer driver. Not
related to mali.

Regards
Henrik
