### ISSUE TITLE
wemac ethernet: problems with IPv6, likely broken multicast

### ISSUE THREAD

**Issue by romanrm** [linux-sunxi/linux-sunxi#59]
Hello,

I observe problems when using IPv6 on the Mele A2000's built-in Ethernet.

IPv6 uses Neighbour Discovery instead of ARP to resolve v6 addresses to MACs, and it relies on multicast.

The most noticeable issue that I have on the Mele (and have also observed on some other systems with broken multicast support) is that the Mele can't be successfully ping6'ed (or contacted in any other way) from another network host, until the Mele itself first initiates a ping6 to that host. After that the connectivity works fine in both directions, but only for a brief period of time.

The Mele also doesn't seem to be able to receive Route Advertisements from the network (which also use multicast).

**Comment by romanrm** [comment]
I see now that the whole thing is just commented out :D https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/sun4i/sun4i_wemac.c#L975 awesome.

**Comment by Vayu** [comment]
There is already some discussion of wemac driver here https://github.com/amery/linux-allwinner/pull/39. This issues can probably be merged

**Comment by romanrm** [comment]
> This issues can probably be merged

That bug is about performance, this bug is about multicast. Two completely different issues.
Or do you advocate merging everything about some particular driver into one huge messy issue about everything.

**Comment by romanrm** [comment]
I have managed to fix it with this patch:

```
--- orig/drivers/net/sun4i/sun4i_wemac.h    2012-06-28 11:56:32.073263842 +0600
+++ fixed/drivers/net/sun4i/sun4i_wemac.h   2012-07-23 14:16:44.868297894 +0600
@@ -180,7 +180,7 @@
 #define EMAC_RX_UCAD        1  //0: Not accept             1: Accept unicast Packets(default)
 #define EMAC_RX_DAF         1  //0: Normal(default)        1: DA Filtering
 #define EMAC_RX_MCO         1  //0: Not accept             1: Accept multicast Packets(default)
-#define EMAC_RX_MHF         1  //0: Disable(default)       1: Enable Hash filter 
+#define EMAC_RX_MHF         0  //0: Disable(default)       1: Enable Hash filter 
 #define EMAC_RX_BCO            1  //0: Not accept             1: Accept Broadcast Packets(default)
 #define EMAC_RX_SAF         0  //0: Disable(default)       1: Enable SA Filtering
 #define EMAC_RX_SAIF        0  //0: Normal(default)        1: Inverse Filtering

```

i.e. disabling the hash filter for multicast. The hash table function is non-functional (commented out) in the link above, so that's why it didn't work.
The multicast now works fine, maybe at the expense of no h/w filtering (my guess is now every multicast packet is passed to the above layers by the driver). But this is much much better than completely broken.
Also according to the comments in the modified line, the hash filter should be disabled by default, so no idea why the constant was set to 1. Every other constant seems to be set according to the "(default)" value in the corresponding comments.
