### ISSUE TITLE
Don't fail horribly if the bootloader used is not the one we prefer

### ISSUE THREAD

**Issue by turl** [linux-sunxi/linux-sunxi#60]
We should still attempt the AW mem check hack if there's no proper ATAG

We should do this because:
1) It's the best way to test the kernels on a new device: knowing the rest of the bootchain works fine, one can test the kernel and be sure it's not some other component failing.
2) There's no uboot that can boot Android boot.img partitions from NAND as far as I'm aware.
3) Lazy people exist :P

**Comment by hno** [comment]
tor 2012-07-26 klockan 12:23 -0700 skrev turl:

> We should still attempt the AW mem check hack if there's no proper ATAG

Which bootloader do not supply an atag or at least command line?

And how do it fail horribly?

Supplying ATAG have been MANDATORY on any ARM Linux bootloaders written
in the last 10+ years.

Even the Allwinner boot.axf do provide ATAG in the form of a precomputed
blob loaded at 0x40000100.

Regards
Henrik

**Comment by turl** [comment]
I don't precisely know if there's no ATAG, or if the ATAG is improper/bad/incorrect; the current code trying to use it however, renders the device unbootable. I don't have serial to debug it further, and I see nothing on ramconsole (ramconsole still holds the last good boot output, so I suppose it doesn't even get to initialize).

**Comment by amery** [comment]
@romanrm just got an ATAG_MEM of 16MB when booting linux directly from `<nanda>linux/linux.in`

**Comment by amery** [comment]
maybe the `.fixup` could be extended to optionally (default y) fallback to the hack when no meminfo is received or... the bootloader is BSing about having less than 256MB?

**Comment by turl** [comment]
sounds good @amery

**Comment by hno** [comment]
fre 2012-07-27 klockan 11:36 -0700 skrev Alejandro Mery:

> maybe the `.fixup` could be extended to optionally (default y) fallback to the hack when no meminfo is received or... the bootloader is BSing about having less than 256MB?

I no atags is provided then the kernel falls back to compile time
defaults, which happens to be 16MB unless overridden by MEM_SIZE.

Not providing any atags is serious wrong configuration and is not
supported. As said even the allwinner bootloader supports supplying
atags, it just don't know how to build them.. instead it's loaded as a
blob.

A normal linux.ini for direct boot from allwinner bootloader not using
u-boot is like

[segment]
img_name = c:\linux\bImage
img_size = 0xb00000
img_base = 0x40008000

[segment]
img_name = c:\linux\params.ini
img_size = 0x1000
img_base = 0x40000000

[script_info]
script_base = 0x43000000
script_size = 0x10000

[logo_info]
logo_name = c:\linux\linux.bmp
logo_show = 1

some variation exists, some load only the atags in second segment, using
0x40000100 as base.

Any efforts spent on adding hacks to the kernel to deal with wrongly
configured bootloaders is a waste imho. Time better spent on configuring
the bootloader correctly.

Regards
Henrik

**Comment by romanrm** [comment]
What is supposed to be in params.ini?

This is how my linux.ini looks, with which I booted in http://lists.phcomp.co.uk/pipermail/arm-netbook/2012-July/005296.html

``` ini
[segment]
img_name = c:\linux\bImage
img_size = 0x2000000
img_base = 0x40008000

[script_info]
script_base = 0x43000000
script_size = 0x10000

[logo_info]
logo_name = c:\linux\linux.bmp
logo_show = 1
```

I believe having some boundaries is useful, e.g. that an A10 device can't have less than 256MB of RAM and also perhaps more than 2 or 3 GB. Much better than trying to boot with clearly wrong info like 16MB or 16PB of RAM like in my dmesg. Also it turns out my SD filesystem was trashed because the kernel tried to boot and operate, but the memory setup was all wrong.

**Comment by amery** [comment]
@hno: where is that default 16MB mem size set?

**update:** don't worry. I found it. `arch/arm/kernel/setup.c:60:#define MEM_SIZE     (16*1024*1024)`

**Comment by amery** [comment]
so something like this should give us a sane default when using broken bootloaders

``` diff
diff --git a/arch/arm/mach-sun4i/include/mach/memory.h b/arch/arm/mach-sun4i/include/mach/memory.h
index f57eb9f..5be06c8 100755
--- a/arch/arm/mach-sun4i/include/mach/memory.h
+++ b/arch/arm/mach-sun4i/include/mach/memory.h
@@ -27,5 +27,7 @@
 /* physical offset of RAM */
 #define PLAT_PHYS_OFFSET               UL(0x40000000)

-#endif
+/* default ATAG_MEM size */
+#define MEM_SIZE       (512*1024*1024)

+#endif
```

**Comment by hno** [comment]
lör 2012-07-28 klockan 00:50 -0700 skrev romanrm:

> What is supposed to be in params.ini?

An atags structure or kernel command line.

kernel command line is easiest to work with.

I think kernel command line goes @0x40000000 and atags @0x40000100 but
it's a little confusing since the A10 kernel have ugly hacks overriding
everything and the information is conflicting.

Regards
Henrik

**Comment by hno** [comment]
Yes it should.

Regards
Henrik

**Comment by amery** [comment]
@turl does it still happen?

**Comment by amery** [comment]
due to lack of confirmation I'm considering this issue closed
