### ISSUE TITLE
drivers/gpu/mali/{mali,ump}/arch

### ISSUE THREAD

**Issue by caminati** [linux-sunxi/linux-sunxi#61]
Those two should be symlinks to 'x' filename, rather than real files containing 'x'.

**Comment by amery** [comment]
they are symlinks. how are you getting the tree? what fs?

**Comment by caminati** [comment]
I am getting the github-packed zip at https://github.com/amery/linux-allwinner/zipball/allwinner-v3.0-android-v2, rather than using git.
I unzip it into an ext3 filesystem. I will try with plain git instead.

**Comment by amery** [comment]
zip doesn't support symlinks, if `git clone` is too much for you, try a tar

**Comment by caminati** [comment]
Whoops, silly me. Thanks
