### ISSUE TITLE
make[2]: warning:  Clock skew detected.  Your build may be incomplete.

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/linux-sunxi#62]
every time compile this kernel ,i got this message : make[2]: warning:  Clock skew detected.  Your build may be incomplete.

**Comment by steev** [comment]
Check the clock on your machine.

**Comment by ghost** [comment]
here my clock settings on /etc/rc.conf :

# LOCALIZATION

# ------------

HARDWARECLOCK="UTC"
TIMEZONE="Asia/Jakarta"
KEYMAP="us"
CONSOLEFONT=
CONSOLEMAP=
LOCALE="en_US.UTF-8"
DAEMON_LOCALE="yes"
USECOLOR="yes"

im using arch linux amd64 ..

**Comment by ghost** [comment]
ok solved after type in the terminal :

$ find . -type f | xargs -n 5 touch
$ make clean
$ make

thanks for your help ..

**Comment by hno** [comment]
lör 2012-07-28 klockan 20:18 -0700 skrev Nizar Lazuardy Firmansyah:

> every time compile this kernel ,i got this message : make[2]: warning:  Clock skew detected.  Your build may be incomplete.

Try a "make clean". If still fails then "rm -rf *; git checkout ."

Regards
Henrik

**Comment by sarfaraj118** [comment]
CC user/module.c
CC user/wiopkd.c
AR build/httpd_app.a
GEN ldscript_memspecific.ld
LD build/httpd.out
/home/sarfaraj/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld:ldscript_memspecific.ld:1: warning: redeclaration of memory region `irom0_0_seg'
/home/sarfaraj/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/httpd.out section`.text' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Makefile.combined:22: recipe for target 'build/httpd.out' failed
make: **\* [build/httpd.out] Error 1

---

how can i remove this error i am installed latest toolchain and SDK .could you tell me how remove warning treat as error ?

**Comment by caioio** [comment]
I am sourcing but it doesn't work
![image](https://user-images.githubusercontent.com/56783709/137646652-2a875499-e358-4f01-9c03-6a11de29f3f8.png)
