### ISSUE TITLE
Mele A2000 kernel panic after commit 9b1b6112465d3fa575966970f315de2c4a023ee1

### ISSUE THREAD

**Issue by pqlaz** [linux-sunxi/linux-sunxi#64]
Use the default configuration sun4i_defconfig, allwinner-v3.0-android-v2 branch

Boot log: http://pastebin.com/swiKLA90

If you replace the files
- drivers/block/sun4i_nand/nfd/mbr.c
- drivers/block/sun4i_nand/nfd/nand_blk.c

on their previous version, the kernel is loaded properly

sorry for my english

**Comment by amery** [comment]
very strange, I can't image anything in 9b1b6112465d3fa575966970f315de2c4a023ee1 affecting `wemac_probe`'s `gpio_request()`s

**Comment by pqlaz** [comment]
Bug occurs when an assembly using binary version of Linaro toolchain (https://launchpad.net/linaro-toolchain-binaries/trunk/2012.07). If compile Linaro toolchain with crosstool-ng, kernel boots normally.

**Comment by amery** [comment]
can you test linaro's toolchain with a clean tree?

**Comment by pqlaz** [comment]
what is meant by "clean tree"?

**Comment by amery** [comment]
basically to run 'make clean' first

**Comment by pqlaz** [comment]
Strange. Now, the bug does not occur. I cleaned the tree before building up to this. Maybe it's a hardware problem
