### ISSUE TITLE
Update mali driver to r3p0

### ISSUE THREAD

**Issue by turl** [linux-sunxi/linux-sunxi#69]
hipboi provided updated mali libs for r3p0 for both gnu/linux and android, so we need to update the kernel land accordingly

See https://github.com/allwinner-dev-team/linux-allwinner/commits/wip/allwinner-3.0/mali-2

There is still some makefile tweaking to do to match the new mali config options, feel free to do it :) Here is an overview of the new CONFIG_ entries involved https://github.com/allwinner-dev-team/linux-allwinner/commit/801dc8a17e53f9a7f10a6a11e30fccb8303fcfc6

!android lib: http://tom.linux-sunxi.org/mali/r3p0_mali400-vg-gles20-linux-ump.tgz
android lib: http://tom.linux-sunxi.org/r3p0.rar

**Comment by amery** [comment]
the `wip/linux-sunxi-3.0/next_mali` branch now has these patches upon 3.0.42

**Comment by amery** [comment]
code for mali_drm merged into the same branch, #77

**Comment by hipboi** [comment]
thank you, @amery.

On Sun, Sep 16, 2012 at 8:08 AM, Alejandro Mery notifications@github.comwrote:

> code for mali_drm merged into the same branch, #77https://github.com/amery/linux-allwinner/issues/77
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/69#issuecomment-8590905.

## 

Keep simple, stay foolish.

**Comment by rzk** [comment]
After fixing DRM stuff, I've discovered that r3p0 libs for linux are most likely not build properly or I miss something. Any app that tries to load them fails with:

```
symbol lookup error: /lib/libGLESv2.so.2: undefined symbol: _vg_image_pbuffer_to_clientbuffer
```

here is nm output http://pastebin.com/MTwKU099

Any suggestions? @hipboi ?

**Comment by hipboi** [comment]
On Sunday, September 16, 2012, Dmitriy Beykun wrote:

> After fixing DRM stuff, I've discovered that r3p0 libs for linux are most
> likely not build properly or I miss something. Any app that tries to load
> them fails with:
> 
> symbol lookup error: /lib/libGLESv2.so.2: undefined symbol: _vg_image_pbuffer_to_clientbuffer
> 
> Any suggestions? @hipboi https://github.com/hipboi ?
> 
> VG? Looks like we need to disable openvg support in Mali DDK. I will ask my
> former workmate release a new lib on Monday.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/69#issuecomment-8594930.

## 

Keep simple, stay foolish.

**Comment by rzk** [comment]
Thanks @hipboi

**Comment by hipboi** [comment]
i have uploaded the r3p0 and r3p1 lib released by my workmate.
http://tom.linux-sunxi.org/r3p0-04rel0.tar.gz
http://tom.linux-sunxi.org/r3p1-01rel0.tar.gz

They are built native on ubuntu-armhf-12.04.

On Mon, Sep 17, 2012 at 12:44 AM, Dmitriy Beykun
notifications@github.com wrote:

> Thanks @hipboi
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Keep simple, stay foolish.

**Comment by hipboi** [comment]
For the built config, see the readme inside the tar.

On Tue, Sep 18, 2012 at 2:25 PM, Tom Cubie mr.hipboi@gmail.com wrote:

> i have uploaded the r3p0 and r3p1 lib released by my workmate.
> http://tom.linux-sunxi.org/r3p0-04rel0.tar.gz
> http://tom.linux-sunxi.org/r3p1-01rel0.tar.gz
> 
> They are built native on ubuntu-armhf-12.04.
> 
> On Mon, Sep 17, 2012 at 12:44 AM, Dmitriy Beykun
> notifications@github.com wrote:
> 
> > Thanks @hipboi
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Keep simple, stay foolish.

## 

Keep simple, stay foolish.
