### ISSUE TITLE
sun4i-vibrator.c:148: undefined reference to `timed_output_dev_register'

### ISSUE THREAD

**Issue by mortaromarcello** [linux-sunxi/linux-sunxi#71]
compiling with CONFIG_SUN4I_VIBRATOR = y the compiler error:sun4i-vibrator.c:148: undefined reference to `timed_output_dev_register'

**Comment by hipboi** [comment]
On Thu, Sep 6, 2012 at 3:22 PM, mortaromarcello notifications@github.comwrote:

> compiling with CONFIG_SUN4I_VIBRATOR = y the compiler
> error:sun4i-vibrator.c:148: undefined reference to
> `timed_output_dev_register'
> 
> the vibrator depends on the android timed out device driver, please also
> choose the timedout device.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/71.

## 

Keep simple, stay foolish.

**Comment by amery** [comment]
so, do we `select` or `depend` in Kconfig ;-)

**Comment by amery** [comment]
fixed by 432d8fad79d33208465a9582e37864bcd352683c
