### ISSUE TITLE
Problem after commit:  sunxi-disp: Add warn prints, fix cache flush... 0165c7d303d8

### ISSUE THREAD

**Issue by Quarx2k** [linux-sunxi/linux-sunxi#72]
https://github.com/amery/linux-allwinner/commit/0165c7d303d8187e5cd0f20af270e1e03b648cbc
This commit made slow updating screen on my ainol aurora.. (like a slow-mode in pc games) 
Display has 60Hz refresh rate.

**Comment by techn** [comment]
https://github.com/techn/linux-allwinner/commit/a418ab0c8233f434a2ae96fcc19ea5a7c5dfdb69

**Comment by amery** [comment]
I really wonder what were they trying to fix with that change....
