### ISSUE TITLE
allwinner mailing list

### ISSUE THREAD

**Issue by polarcat** [linux-sunxi/linux-sunxi#73]
It would be good to have dedicated mailing list for technical discussions related to allwinner adaptation alongside with patch review. It may also help to draw attention of AllWinner team and gradually get them involved :)

**Comment by hipboi** [comment]
On Tue, Sep 11, 2012 at 5:59 PM, Aliaksei Katovich <notifications@github.com

> wrote:
> 
> It would be good to have dedicated mailing list for technical discussions
> related to allwinner adaptation alongside with patch review. It may also
> help to draw attention of AllWinner team and gradually get them involved :)
> 
>  i don't think so. Allwinner is very product oriented. Allwinner engineer
> is very busy of a lot of things, not only the bug of Allwinner internal,
> but also the bugs from the customers. Besides, English is another problem.
> But i think to have a mail list to review patches is a good idea.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/73.

## 

Keep simple, stay foolish.

**Comment by amery** [comment]
I would like it to be something like `dev@linux-sunxi.org`. it would be great if someone already managing other mailing lists can host it... if not we can always install mailman in the same server that hosts the wiki and cubieboard.org

**Comment by hipboi** [comment]
On Tue, Sep 11, 2012 at 6:12 PM, Alejandro Mery notifications@github.comwrote:

> I would like it to be something like dev@linux-sunxi.org. it would be
> great if someone already managing other mailing lists can host it... if not
> we can always install mailman in the same server that hosts the wiki and
> cubieboard.org
> 
> i like dev@linux-sunxi.org : )
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/73#issuecomment-8454992.

## 

Keep simple, stay foolish.

**Comment by amery** [comment]
@hipboi it would be seriously amazing if allwinner would authorize other engineers to join and help us improve the public kernel... even if their english is not as good as yours ;-)

**Comment by hipboi** [comment]
On Tue, Sep 11, 2012 at 6:28 PM, Alejandro Mery notifications@github.comwrote:

> @hipboi https://github.com/hipboi it would be seriously amazing if
> allwinner would authorize other engineers to join and help us improve the
> public kernel... even if their english is not as good as yours ;-)
> 
> Not authorizing, it's they have no effort. Btw, i just quit my job at
> allwinner. My boss told me "you can come back in the future". Maybe he is
> just polite. But i will work for allwinner till this week. i need to look
> after my wife and my coming baby, so i can not stay at Zhuhai.
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/amery/linux-allwinner/issues/73#issuecomment-8455270.

## 

Keep simple, stay foolish.

**Comment by rzk** [comment]
@hipboi Is there any chance to get help from you with sun5i u-boot-mmc (u-boot boots ok from sdcard, but kernel dies at any printk) and new r3p1-01rel0 mali400 libs & drivers before you completely quit allwinner?

**Comment by amery** [comment]
@rzk please open a separated ticket for that.

**Comment by hno** [comment]
tis 2012-09-11 klockan 05:12 -0700 skrev Dmitriy Beykun:

> @hipboi Is there any chance to get help from you with sun5i u-boot-mmc
> (u-boot boots ok from sdcard, but kernel dies at any printk) and new
> r3p1-01rel0 mali400 libs & drivers before you completely quit
> allwinner?

I have u-boot fairly under control now.

Regards
Henrik

**Comment by polarcat** [comment]
anyone any experience with http://www.freelists.org?

**Comment by amery** [comment]
I got a reply from vger.kernel.org and they consider we should just use linux-arm's list....

I've temporarily created https://groups.google.com/forum/?fromgroups#!forum/linux-sunxi linux-sunxi@googlegroups.com...

I'm really inclined for `dev@linux-sunxi.org` ... but I would need some time to learn how to set it up :<

comments? @hno?

**Comment by npeacock** [comment]
I've posted an issue to the list, actually did it twice because I thought the first one didn't make it.  I hope someone else has actually signed up to see it ;-)

**Comment by amery** [comment]
It was awaiting moderation :p (first post from new member)
