### ISSUE TITLE
Sun5i doesn`t build  mali modules

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/linux-sunxi#74]
I got this error with allwinner-v3.0-android-v2 branch and I used sun5i_defconfig:
 CC [M]  drivers/gpu/mali/mali/common/mali_kernel_core.o
arm-eabi-gcc: katalog: No such file or directory
arm-eabi-gcc: katalog": No such file or directory
<command-line>: warning: missing terminating " character
In file included from /home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/common/mali_pp_job.h:19,
                 from /home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/common/mali_pp.h:15,
                 from /home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/common/mali_group.h:19,
                 from /home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/common/mali_dlbu.h:15,
                 from /home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/common/mali_kernel_core.c:21:
/home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/regs/mali_200_regs.h:102:2: error: #error "No supported mali core defined"
/home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/regs/mali_200_regs.h:124:2: error: #error "No supported mali core defined"
/home/willing/Android/cyanogenmod9/kernel/drivers/gpu/mali/mali/regs/mali_200_regs.h:147:2: error: #error "No supported mali core defined"
make[6]: **\* [drivers/gpu/mali/mali/common/mali_kernel_core.o] Błąd 1
make[5]: **\* [drivers/gpu/mali/mali] Błąd 2
make[4]: **\* [drivers/gpu/mali] Błąd 2
make[3]: **\* [drivers/gpu] Błąd 2

**Comment by turl** [comment]
Did you use git to get the source, or did you download a zip from github?

**Comment by ghost** [comment]
I added it manifest.xml, so it was downloaded from git.

**Comment by ghost** [comment]
I removed source and sync everything again, and it's building fine, but it doesn`t boot correct. I can debug it now, because I fried may rs232ttl usb dongle.

**Comment by techn** [comment]
Works for me

**Comment by techn** [comment]
@WillingMagic Didn't read your last post. Btw. for sun5i  the preferred config is a13_defconfig. Also I think enabling tmpfs fixed this your issue.
