### ISSUE TITLE
Multitouch doesn't work with X

### ISSUE THREAD

**Issue by npeacock** [linux-sunxi/linux-sunxi#80]
This is related to a previous issue, but I have been using the ft5x driver on my A10 tablet.  Basically to use the touch screen in Linux you have to disable multitouch.  Also the driver did not honor the swap and invert settings in the .fex files once multitouch is disabled.

I have written a fix that adds a config option.  I haven't done this before but I think you just need this to find the commit right?  f0c9753483e965bce180dab4cbcc09705e35abc9

and followed with another commit because everyone was going to complain about the C++ style comments (that were already there)  in the commit, so I cleared them out of the two files 7dda6ace3c371c742beeb0d2732277176b60b114

I should mention I found a handy function for fixing the comments,  sed -i "s?//(._)?/_\1 */?" <filename>

**Comment by amery** [comment]
why not making `TOUCHSCREEN_FT5X_TS_MULTI` depend on `ANDROID` then? ... about the cleanup, some of those should be `#if 0 .. #endif`

also, to start getting mainline-ish.... can you post this to linux-sunxi@googlegroups.com (https://groups.google.com/forum/#!forum/linux-sunxi) using `git send-email` and friends ? :)

**Comment by techn** [comment]
@npeacock would it be better change TOUCHSCREEN_FT5X_TS_MULTI to FT5X0X_MULTITOUCH and removing #define CONFIG_FT5X0X_MULTITOUCH?

**Comment by npeacock** [comment]
I want to try and come back to fix the multitouch for linux later so we can have pinch gestures and all.  So I don't want it to depend on Android. 

@techn I guess that would work too.

**Comment by npeacock** [comment]
After some hijinks I think I have sent it successfully to the mailing list.

**Comment by npeacock** [comment]
https://github.com/amery/linux-allwinner/commit/202a72c5d1d5eaf9955ae11320c1ed39de584340\

This commit has fixed the real problem, my patch now only fixed honoring the inverted settings in single touch mode, which will probably never be used.

**Comment by amery** [comment]
@npeacock the fixes in that commit were just merged into our main branch (3.0-v2), see b32a25f543e23503002ec2d4a164bca502df6868. can you confirm it's working all right and resubmit (to the mailing list) the parts of your patch that you consider still relevant? Thanks!
