### ISSUE TITLE
How to include device specific driver for Allwinner a10 board

### ISSUE THREAD

**Issue by vasanths** [linux-sunxi/linux-sunxi#81]
Hi, 

I am building a custom ROM for a device with All-winner a10 Board. The device much similar to  EKEN a10 device.  I have successful build the kernel and the android source. Can you help me  how to pull and include the device specific driver . 

Any information regarding how to include the custom driver and build the OS to form a single firmware IMG file will be greatly appreciated .

Note : Device specification ref : http://green-power.en.alibaba.com/product/572349288-213925756/9_7_inch_IPS_Capacitive_screen_ALLWinner_A10_1_5GHZ_CPU_1GB_RAM_HDMI_tablet_pc_android_4_0.html

Thank you in Advance .

**Comment by amery** [comment]
sure. where are the sources?

**Comment by vasanths** [comment]
I am building AOSP and i got the kernel from your github host linux-allwinner kernel. I am not sure how to make this into device specific build. The tablet device i have already runs Android 4.0.3 . I am not sure which sources you are asking ?

**Comment by amery** [comment]
so you mean the driver is already in our tree? simple enable it in .config doing something like:

``` sh
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- sun4i_crane_defconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- menuconfig
cp .config arch/arm/configs/mytablet_defconfig
```

and then modify the build script to use that `mytable_defconfig` instead of `sun4i_crane_defconfig`

**Comment by vasanths** [comment]
For the device i have i am not sure the driver in the tree will work or not . Can i pull the driver files from the device itself and use it for building ? If yes please let me know how and from which location i need to get the driver from the device ? And where exactly i need to add it?

**Comment by amery** [comment]
this ended up been a android support question and invalid to this issue tracker. please try on the arm-netbook mailing list or on one of the several android forums. I'm closing the ticket. I'm sorry to not been able to help you farther.

**Comment by vasanths** [comment]
Thank you for your response .
