### ISSUE TITLE
sun4i-gpio driver don't unload

### ISSUE THREAD

**Issue by vinifr** [linux-sunxi/linux-sunxi#82]
I called "fd = open ("/dev/sun4i-gpio", O_RDWR);" but I forgot call close(). Now i can't unload sun4i-gpio driver, even after a reset... I am not sure, but before it unloaded normally.

```
# modprobe -r sun4i-gpio
[  101.720000] Unable to handle kernel NULL pointer dereference at virtual address 0000001c
[  101.730000] pgd = d9b10000
[  101.730000] [0000001c] *pgd=57daf831, *pte=00000000, *ppte=00000000
[  101.740000] Internal error: Oops: 17 [#1] PREEMPT
[  101.740000] Modules linked in: sun4i_gpio(-) rtl8192cu rtl8192c_common rtlwifi
[  101.740000] CPU: 0    Not tainted  (3.0.42+ #1)
[  101.740000] PC is at sysfs_find_dirent+0x4/0x5c
[  101.740000] LR is at sysfs_get_dirent+0x28/0x78
[  101.740000] pc : [<c013f82c>]    lr : [<c013f8ac>]    psr: 60000013
[  101.740000] sp : d6e31ef8  ip : 00000000  fp : 00000001
[  101.740000] r10: 00000000  r9 : d6e30000  r8 : c0033de8
[  101.740000] r7 : 01bbfe30  r6 : 00000000  r5 : bf0e44a8  r4 : 00000000
[  101.740000] r3 : 00000000  r2 : bf0e44a8  r1 : 00000000  r0 : 00000000
[  101.740000] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[  101.740000] Control: 10c5387d  Table: 59b10019  DAC: 00000015
...
```

Complete log: http://dl.dropbox.com/u/22273442/fault.txt

**Comment by wingrime** [comment]
please compile kernel with debug symbols, this addresses not mean anything at all

**Comment by vinifr** [comment]
Strange, the option CONFIG_DEBUG_INFO is set to Y. This is the config correct or there is other?

**Comment by wingrime** [comment]
Sorry, I saw driver code and can say that /dev/gpio-sun4i not Implemented it stud all control can be done over sysfs

**Comment by vinifr** [comment]
If you want, I have script.fex: http://dl.dropbox.com/u/22273442/script.fex. To gpio_para I edited this way:
[gpio_para]
gpio_used = 1
gpio_num = 5
gpio_pin_1 = port:PB02<1><0><default><default>
gpio_pin_2 = port:PB03<1><0><default><default>
gpio_pin_3 = port:PB04<1><0><default><default>
gpio_pin_4 = port:PB05<1><0><default><default>
gpio_pin_5 = port:PG09<1><1><default><default>

I am with little problem in board, but I'll try to test.

**Comment by wingrime** [comment]
teset over sysfs interface

inputdevice is stud

**Comment by vinifr** [comment]
insmod/rmmod presents the same error

**Comment by wingrime** [comment]
It easy to fix, but perhaps it may be useless becos this device need for compartiblity with kernel music_device class, that means, that device file simply needed for registation sysfs interface, that used for gpio control. you cannt control anything overthat file (you can implement it if you want over ioctl) control over sysfs file

**Comment by wingrime** [comment]
patch sended to mail list please close issue when tested

**Comment by vinifr** [comment]
Thanks for help. But could you to pass me the link to the branch which you sent?
Tomorrow i can to test.
