### ISSUE TITLE
3.4 doesn't build

### ISSUE THREAD

**Issue by turl** [linux-sunxi/linux-sunxi#83]
3.4 build fails with the following

drivers/built-in.o: In function `rmmod_device_driver':
~/linux-allwinner/drivers/usb/sun4i_usb/manager/usb_msg_center.c:268: undefined reference to`sw_usb_device_disable'
drivers/built-in.o: In function `insmod_device_driver':
~/linux-allwinner/drivers/usb/sun4i_usb/manager/usb_msg_center.c:240: undefined reference to`sw_usb_device_enable'
make: **\* [.tmp_vmlinux1] Error 1

**Comment by amery** [comment]
sun4i_crane_defconfig? this is most likely related to #29

**Comment by turl** [comment]
I used https://github.com/allwinner-dev-team/linux-allwinner/commit/74c0cd3f992c480f33ffccf96fa157261e8c5317 + 'make oldconfig'
