### ISSUE TITLE
gt811_ts not working

### ISSUE THREAD

**Issue by psachin** [linux-sunxi/linux-sunxi#95]
I tried sunxi gt811_ts driver but still no success.  It creates /dev/input/event1. Output of 'cat /dev/input/event1' also responds to touch. Do I need to install or configure something else ? I m using ubuntu-core 12.04 with xorg, lxde installed

kernel logs -->

===========================goodix_ts_init=====================
[    1.210000] ctp_fetch_sysconfig_para.
[    1.220000] ctp_fetch_sysconfig_para: after: ctp_twi_addr is 0x5d,
dirty_addr_buf: 0x5d. dirty_addr_buf[1]: 0xfffe
[    1.230000] ctp_fetch_sysconfig_para: ctp_twi_id is 1.
[    1.230000] ctp_fetch_sysconfig_para: screen_max_x = 800.
[    1.240000] ctp_fetch_sysconfig_para: screen_max_y = 480.
[    1.240000] ctp_fetch_sysconfig_para: revert_x_flag = 0.
[    1.250000] ctp_fetch_sysconfig_para: revert_y_flag = 0.
[    1.250000] ctp_fetch_sysconfig_para: exchange_x_y_flag = 0.
[    1.260000] goodix_ts_init: after fetch_sysconfig_para:
normal_i2c: 0x5d. normal_i2c[1]: 0xfffe
[    1.270000] script parser fetch err.
[    1.270000] ctp_init_platform_resource: tp_reset request gpio fail!
[    1.280000] i2c-core: driver [Goodix-TS] using legacy suspend
method
[    1.280000] i2c-core: driver [Goodix-TS] using legacy resume method
[    1.290000] ctp_detect: Detected chip Goodix-TS at adapter 1,
address 0x5d
[    1.300000] Goodix-TS 1-005d: Install gt811 driver.
[    1.300000] Goodix-TS 1-005d: Driver Release Date:2012-02-08
[    1.310000] ======goodix_gt811 probe======
[    1.440000] ctp_set_irq_mode: config gpio to int mode.
[    1.440000] ctp_set_irq_mode, 231: gpio_int_info, port = 7,
port_num = 11.
[    1.450000]  INTERRUPT CONFIG
[    1.460000] Goodix-TS 1-005d: GT811 init
info:X_MAX=4096,Y_MAX=4096,TRIG_MODE=RISING EDGE
[    1.480000] input: gt80x as /devices/virtual/input/input1
[    1.680000] Goodix-TS 1-005d: GT811 Verion:0x2010
[    1.680000] Goodix-TS 1-005d: Start gt80x in interrupt mode,Driver

**Comment by techn** [comment]
Works for me. I have a13_mid tablet and latest linaro ALIP rootfs.
I think this is user space problem.

**Comment by srikantpatnaik** [comment]
@techn :+1: did you disabled multi touch for goodix? 
We have another ft5x tablet on which we have to disable multitouch.

**Comment by techn** [comment]
I'm using driver from repo without modifications. And there seems to
be GOODIX_MULTI_TOUCH enabled.

2012/11/5 Srikant notifications@github.com

**Comment by amery** [comment]
@srikantpatnaik: `ft5x` is supposed to work fine with multi touch these days

**Comment by npeacock** [comment]
I'm actually still having trouble, I misinterpreted an earlier test.  Others report no problems though, so maybe both mine and this issue are in user space.  Especially since the /dev is giving output.

Alejandro Mery notifications@github.com wrote:

> @srikantpatnaik: `ft5x` is supposed to work fine with multi touch these
> days
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-sunxi/linux-sunxi/issues/95#issuecomment-10089902

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by psachin** [comment]
gt811 worked !!

I tested with linaro's ALIP rootfs which was having lxde as default DE, it works without any modification.
'utouch' was missing in ubuntu-core. I installed it and it worked.

thanx a lot guys :)
