### ISSUE TITLE
wemac crash after  6a7a8bd1adced6d0da860b004eb4967dae2a3d00

### ISSUE THREAD

**Issue by BobRyan530** [linux-sunxi/linux-sunxi#97]
git revert 6a7a8bd1adced6d0da860b004eb4967dae2a3d00
fixed my crash http://pastebin.com/3vKTESfi

I was asked by Turl to paste links to these files for my mele A2000 v1.7 device (A10 rev C)
http://bob.drinksbeer.org/script.fex
http://bob.drinksbeer.org/script.bin

**Comment by turl** [comment]
I see emac_power is empty, maybe script_parser_fetch sets db->mos_gpio in a broken way then, and causes the crash?

@amery thoughts? :)

**Comment by amery** [comment]
strangely the same empty emac_power doesn't crash in the cubie. thanks for the report.

**Comment by amery** [comment]
@bsdfox: can you try http://sprunge.us/LiOH ?

**Comment by amery** [comment]
I've commited the change as 09946bae6c414e62c066c57169100c62cd303500.

@bsdfox can you confirm it solved the issue?

**Comment by BobRyan530** [comment]
Yes, I can confirm this solved my issue. 

----- Original Message -----
