### ISSUE TITLE
3.4: cannot build uImage

### ISSUE THREAD

**Issue by ghost** [linux-sunxi/linux-sunxi#98]
I try to build uImage on a Debian box, which is prepared like this ([How To Build Debian From Source Code for Mele](http://rhombus-tech.net/allwinner_a10/hacking_the_mele_a1000/Building_Debian_From_Source_Code_for_Mele/)):

``` shell
apt-get install emdebian-archive-keyring
apt-get install gcc-4.4-arm-linux-gnueabi
apt-get build-essential git
apt-get uboot-mkimage
apt-get libusb-1.0-0-dev
```

I am following the guide at [FirstSteps](http://linux-sunxi.org/FirstSteps) and have done all instructions without errors.

`make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- sun4i_defconfig` works, but `make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -j5 uImage` fails:

``` shell
  LD      .tmp_vmlinux1
arch/arm/common/built-in.o: In function `sp804_get_clock_rate':
timer-sp.c:(.init.text+0x31c): undefined reference to `clk_get_sys'
timer-sp.c:(.init.text+0x364): undefined reference to `clk_put'
timer-sp.c:(.init.text+0x398): undefined reference to `clk_put'
arch/arm/mach-versatile/built-in.o: In function `versatile_init_early':
versatile_ab.c:(.init.text+0x134): undefined reference to `clkdev_add_table'
drivers/built-in.o: In function `clcdfb_remove':
hid-input.c:(.text+0xd790): undefined reference to `clk_put'
drivers/built-in.o: In function `clcdfb_probe':
hid-input.c:(.text+0xdc70): undefined reference to `clk_get'
hid-input.c:(.text+0xde04): undefined reference to `clk_put'
drivers/built-in.o: In function `amba_get_enable_pclk':
hid-input.c:(.text+0xe448): undefined reference to `clk_get'
hid-input.c:(.text+0xe470): undefined reference to `clk_put'
drivers/built-in.o: In function `amba_put_disable_pclk':
hid-input.c:(.text+0xe49c): undefined reference to `clk_put'
drivers/built-in.o: In function `pl011_remove':
hid-input.c:(.text+0x2b6c4): undefined reference to `clk_put'
drivers/built-in.o: In function `pl011_probe':
hid-input.c:(.text+0x2c234): undefined reference to `clk_get'
hid-input.c:(.text+0x2c318): undefined reference to `clk_put'
drivers/built-in.o: In function `enable_clock':
hid-input.c:(.text+0x3a004): undefined reference to `clk_get'
hid-input.c:(.text+0x3a01c): undefined reference to `clk_put'
drivers/built-in.o: In function `disable_clock':
hid-input.c:(.text+0x3a044): undefined reference to `clk_get'
hid-input.c:(.text+0x3a05c): undefined reference to `clk_put'
drivers/built-in.o: In function `__pm_clk_remove':
hid-input.c:(.text+0x3a1b8): undefined reference to `clk_put'
drivers/built-in.o: In function `pm_clk_add':
hid-input.c:(.text+0x3a424): undefined reference to `clk_get'
drivers/built-in.o: In function `mmc_io_rw_extended':
hid-input.c:(.text+0x6d9ac): undefined reference to `sunximmc_check_r1_ready'
drivers/built-in.o: In function `amba_kmi_probe':
hid-input.c:(.devinit.text+0x8bc): undefined reference to `clk_get'
drivers/built-in.o: In function `amba_kmi_remove':
hid-input.c:(.devexit.text+0xd4): undefined reference to `clk_put'
make: *** [.tmp_vmlinux1] Fel 1
```

Here is a complete dump: http://pastie.org/5351582

The targets `modules` and `modules_install` works fine. Revision: 29c9109738eeac08ae804ca70cb38f48cb79ce6e "net: sun4i-wemac: fix support for NULL emac_power "

**Comment by ghost** [comment]
hard-reset back to tag "v3.5" works, appearently.

**Comment by amery** [comment]
what? we have 3.0 and 3.4 branches. resetting to v3.5 send you out of the sunxi kernel.

**Comment by ghost** [comment]
Ooops, my bad.

Anyway, hard-reseting back to origin/sunxi-3.4 results in the error already described. Should I reset to an older commit in the 3.4 branch?

**Comment by amery** [comment]
please paste your .config somewhere

**Comment by ghost** [comment]
http://pastie.org/5352218

**Comment by amery** [comment]
that is from a 3.0.42, not 3.4.5

**Comment by romanrm** [comment]
Also this is not a config for an Allwinner device:

> CONFIG_ARCH_VERSATILE=y

but rather for http://www.arm.com/products/tools/development-boards/versatile/index.php

**Comment by ghost** [comment]
I have cloned a fresh linux-sunxi and checked out to sunxi-3.4 now, this is the .config it generated after I restarted fresh:

http://pastie.org/5352502

I also found out, thanks to @romanrm, I have mistakenly written `defconfig` instead of `sun4i_defconfig`. 

Running `sun4i_defconfig` and then `uImage`, however, still do not create the uImage file. This is the log:

http://pastie.org/5352569

**Comment by amery** [comment]
just fixed that. update

**Comment by ghost** [comment]
Worked like a charm now! THANK YOU!
