### ISSUE TITLE
video/sunxi: wrong path to axp-gpio.h

### ISSUE THREAD

**Issue by nikel123** [linux-sunxi/linux-sunxi#99]
patch for sunxi-3.0 branch

<pre>
From d91fe3f1ba4f2bf6d024a5a7627e5d9e34823d63 Mon Sep 17 00:00:00 2001
From: Andrej Gelenberg <andrej.gelenberg@udo.edu>
Date: Sun, 18 Nov 2012 13:47:48 +0100
Subject: [PATCH] video/sunxi: fix path to axp-gpio.h

Signed-off-by: Andrej Gelenberg <andrej.gelenberg@udo.edu>

---
 drivers/video/sunxi/disp/OSAL_Pin.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/video/sunxi/disp/OSAL_Pin.c b/drivers/video/sunxi/disp/OSAL_Pin.c
index df76f58..d4c0fca 100644
--- a/drivers/video/sunxi/disp/OSAL_Pin.c
+++ b/drivers/video/sunxi/disp/OSAL_Pin.c
@@ -21,7 +21,7 @@
 #include "OSAL_Pin.h"

 #ifdef CONFIG_ARCH_SUN5I
-#include "../../../../power/axp_power/axp-gpio.h"
+#include "../../../power/axp_power/axp-gpio.h"
 #endif

 __hdle OSAL_GPIO_Request(user_gpio_set_t *gpio_list, __u32 group_count_max)
-- 
1.8.0
</pre>

**Comment by rzk** [comment]
Please send this to our ML http://linux-sunxi.org/Mailing_list (read http://linux-sunxi.org/Submitting_patches)

**Comment by turl** [comment]
Is this still an issue?

**Comment by amery** [comment]
it's fixed already. I'm closing the ticket.
